call AccountCoverageManagementTest.bat
cd RunFiles/QA
call AccountTearSheetArchiveTest.bat
cd RunFiles/QA
call AccountTearSheetTest.bat
cd RunFiles/QA
call ActivityShowFilter.bat
cd RunFiles/QA
call ActivityTest.bat
cd RunFiles/QA
call AddContactTest.bat
cd RunFiles/QA
call AddCorporateAccountTest.bat
cd RunFiles/QA
call AddCoverage.bat
cd RunFiles/QA
call AddCoverageFromTickerTearSheet.bat
cd RunFiles/QA
call AddCoverageWithSector.bat
cd RunFiles/QA
call AddInteractionTest.bat
cd RunFiles/QA
call AddInvestorAccountTest.bat
cd RunFiles/QA
call AddNewContactTest.bat
cd RunFiles/QA
call AddRecommendationTest.bat
cd RunFiles/QA
call AddServiceAccountTest.bat
cd RunFiles/QA
call BulkCallTest.bat
cd RunFiles/QA
call BulkEmploymentChangeTest.bat
cd RunFiles/QA
call BulkSubscription.bat
cd RunFiles/QA
call ContactRelationshipTest.bat
cd RunFiles/QA
call ContactTearSheetHeadersVerify.bat
cd RunFiles/QA
call ContactTearSheetTest.bat
cd RunFiles/QA
call DashboardTest.bat
cd RunFiles/QA
call FloatingATSTest.bat
cd RunFiles/QA
call FloatingCTSTest.bat
cd RunFiles/QA
call GlobalSearchTest.bat
cd RunFiles/QA
call LibraryPortalTest.bat
cd RunFiles/QA
call MarModuleTest.bat
cd RunFiles/QA
call MyContactsTest.bat
cd RunFiles/QA
call MyListTest.bat
cd RunFiles/QA
call NewContactTest.bat
cd RunFiles/QA
call ProspectTest.bat
cd RunFiles/QA
call ReaderShipEmailModule.bat
cd RunFiles/QA
call ReaderShipModule.bat
cd RunFiles/QA
call RelationshipEnhancements.bat
cd RunFiles/QA
call ReportTest.bat
cd RunFiles/QA
call ResearchLibraryModuleTest.bat
cd RunFiles/QA
call ResearchSalesPeronTearsheet.bat
cd RunFiles/QA
call RevenueAdvancedAllTableHeaders.bat
cd RunFiles/QA
call RevenueAdvancedTest.bat
cd RunFiles/QA
call RevenueModule.bat
cd RunFiles/QA
call RevenueTableExample.bat
cd RunFiles/QA
call RevenueTest.bat
cd RunFiles/QA
call ROITest.bat
cd RunFiles/QA
call SalesTraderTearSheetTest.bat
cd RunFiles/QA
call ServiceAccountTest.bat
cd RunFiles/QA
call SponserCompaniesTab.bat
cd RunFiles/QA
call SuperAccountTest.bat
cd RunFiles/QA
call TickerCoverageManagementTest.bat
cd RunFiles/QA
call TickerTearSheetTest.bat
cd RunFiles/QA
call TopResearchSalesPerson.bat
cd RunFiles/QA
call TopSalesTradersGrossComm.bat
cd RunFiles/QA
call TradesModule.bat
cmd /k
