call AccountCoverageManagementTest1.bat
cd RunFiles/WB
call AccountCoverageManagementTest2.bat
cd RunFiles/WB
call AccountTearSheetArchiveTest.bat
cd RunFiles/WB
call AccountTearsheetBulkAddContactTest.bat
cd RunFiles/WB
call AccountTearsheetBulkEditContactTest.bat
cd RunFiles/WB
call AccountTearSheetTest1.bat
cd RunFiles/WB
call AccountTearSheetTest2.bat
cd RunFiles/WB
call AccountTearSheetTest3.bat
cd RunFiles/WB
call AccountTearSheetTest4.bat
cd RunFiles/WB
call ActivityShowFilter.bat
cd RunFiles/WB
call ActivityTest.bat
cd RunFiles/WB
call AddContactTest.bat
cd RunFiles/WB
call AddCorporateAccountTest.bat
cd RunFiles/WB
call AddCoverage.bat
cd RunFiles/WB
call AddCoverageFromTickerTearSheet.bat
cd RunFiles/WB
call AddCoverageWithSector.bat
cd RunFiles/WB
call AddInteractionTest1.bat
cd RunFiles/WB
call AddInteractionTest2.bat
cd RunFiles/WB
call AddInteractionTest3.bat
cd RunFiles/WB
call AddInvestorAccountTest.bat
cd RunFiles/WB
call AddNewContactTest.bat
cd RunFiles/WB
call AddRecommendationTest1.bat
cd RunFiles/WB
call AddRecommendationTest2.bat
cd RunFiles/WB
call AddServiceAccountTest.bat
cd RunFiles/WB
call AddTestDataUsingApi.bat
cd RunFiles/WB
call AnalystTearsheetTest.bat
cd RunFiles/WB
call BulkAddContactsTest1.bat
cd RunFiles/WB
call BulkAddContactsTest2.bat
cd RunFiles/WB
call BulkAddContactsTest3.bat
cd RunFiles/WB
call BulkCallTest.bat
cd RunFiles/WB
call BulkEmploymentChangeTest.bat
cd RunFiles/WB
call BulkMoveTest.bat
cd RunFiles/WB
call BulkSubscription.bat
cd RunFiles/WB
call CalendarTest.bat
cd RunFiles/WB
call ClosedDealsTest.bat
cd RunFiles/WB
call ContactRelationshipTest.bat
cd RunFiles/WB
call ContactTearSheetTest1.bat
cd RunFiles/WB
call ContactTearSheetTest2.bat
cd RunFiles/WB
call ContactTearSheetTest3.bat
cd RunFiles/WB
call ContactTearSheetTest4.bat
cd RunFiles/WB
call CustomSubscriptionsTest.bat
cd RunFiles/WB
call DashboardTest1.bat
cd RunFiles/WB
call DashboardTest2.bat
cd RunFiles/WB
call DashboardTest3.bat
cd RunFiles/WB
call DashboardTest4.bat
cd RunFiles/WB
call DocumentCriteriaMappingTest.bat
cd RunFiles/WB
call EmailsModuleTest.bat
cd RunFiles/WB
call EventManagerTest1.bat
cd RunFiles/WB
call EventManagerTest2.bat
cd RunFiles/WB
call EventManagerTest3.bat
cd RunFiles/WB
call EventManagerTest4.bat
cd RunFiles/WB
call FloatingATSTest.bat
cd RunFiles/WB
call FloatingCTSTest.bat
cd RunFiles/WB
call FloatingTTSTest.bat
cd RunFiles/WB
call GlobalSearchTest.bat
cd RunFiles/WB
call LibraryPortalTest.bat
cd RunFiles/WB
call MarModuleTest.bat
cd RunFiles/WB
call MyContactsTest1.bat
cd RunFiles/WB
call MyContactsTest2.bat
cd RunFiles/WB
call MyListDynamicFiltersTest.bat
cd RunFiles/WB
call MyListTest1.bat
cd RunFiles/WB
call MyListTest2.bat
cd RunFiles/WB
call MyListTest3.bat
cd RunFiles/WB
call NewContactTest.bat
cd RunFiles/WB
call ProcedureSummaryTest.bat
cd RunFiles/WB
call ProspectTest.bat
cd RunFiles/WB
call QuickLookBulkAddContactsTest1.bat
cd RunFiles/WB
call QuickLookBulkAddContactsTest2.bat
cd RunFiles/WB
call QuickLookBulkAddContactsTest3.bat
cd RunFiles/WB
call ReaderShipEmailModule.bat
cd RunFiles/WB
call ReaderShipModule.bat
cd RunFiles/WB
call RelationshipEnhancements.bat
cd RunFiles/WB
call ReportTest.bat
cd RunFiles/WB
call ResearchLibraryModuleTest.bat
cd RunFiles/WB
call ResearchSalesPeronTearsheet.bat
cd RunFiles/WB
call ResearchSubscriptionVTest1.bat
cd RunFiles/WB
call ResearchSubscriptionVTest2.bat
cd RunFiles/WB
call RevenueAdvancedAllTableHeaders.bat
cd RunFiles/WB
call RevenueAdvancedTest1.bat
cd RunFiles/WB
call RevenueAdvancedTest2.bat
cd RunFiles/WB
call RevenueModule.bat
cd RunFiles/WB
call RevenueTest1.bat
cd RunFiles/WB
call RevenueTest2.bat
cd RunFiles/WB
call ROITest.bat
cd RunFiles/WB
call RoleNavigationTest.bat
cd RunFiles/WB
call SalesTraderTearSheetTest.bat
cd RunFiles/WB
call ServiceAccountTearsheetBulkAddContactTest.bat
cd RunFiles/WB
call ServiceAccountTearsheetBulkEditTest.bat
cd RunFiles/WB
call ServiceAccountTest1.bat
cd RunFiles/WB
call ServiceAccountTest2.bat
cd RunFiles/WB
call SponserCompaniesTab.bat
cd RunFiles/WB
call SuperAccountBulkEditTest.bat
cd RunFiles/WB
call SuperAccountTest.bat
cd RunFiles/WB
call TickerCoverageManagementTest1.bat
cd RunFiles/WB
call TickerCoverageManagementTest2.bat
cd RunFiles/WB
call TickerTearsheetBulkAddContactTest.bat
cd RunFiles/WB
call TickerTearsheetBulkEditContactTest.bat
cd RunFiles/WB
call TickerTearSheetTest1.bat
cd RunFiles/WB
call TickerTearSheetTest2.bat
cd RunFiles/WB
call TickerTearSheetTest3.bat
cd RunFiles/WB
call TopResearchSalesPerson.bat
cd RunFiles/WB
call TopSalesTradersGrossComm.bat
cd RunFiles/WB
call TradesModule.bat
cd RunFiles/WB
call UnsubscribeRequestsTest.bat
cmd /k
