call AccountTearSheetTest.bat
cd RunFiles/MIZUHO
call AddContactTest.bat
cd RunFiles/MIZUHO
call AnalystTearsheetTest.bat
cd RunFiles/MIZUHO
call ClosedDealsTest.bat
cd RunFiles/MIZUHO
call ContactTearSheetTest.bat
cd RunFiles/MIZUHO
call DashboardTest.bat
cd RunFiles/MIZUHO
call DashboardTestWidgets.bat
cd RunFiles/MIZUHO
call MyContactsTest.bat
cd RunFiles/MIZUHO
call MyListTest.bat
cd RunFiles/MIZUHO
call ReaderShipEmailModule.bat
cd RunFiles/MIZUHO
call ReaderShipModule.bat
cd RunFiles/MIZUHO
call ResearchLibraryModuleTest.bat
cd RunFiles/MIZUHO
call ResearchSalesPeronTearsheet.bat
cd RunFiles/MIZUHO
call RevenueModule.bat
cd RunFiles/MIZUHO
call RevenueTest.bat
cd RunFiles/MIZUHO
call SalesTraderTearSheetTest.bat
cd RunFiles/MIZUHO
call ServiceAccountTest.bat
cd RunFiles/MIZUHO
call TickerTearSheetTest.bat
cd RunFiles/MIZUHO
call TradesModule.bat
cmd /k
