call ContactTearSheetHeadersVerify.bat
cd RunFiles/CHARDAN
call ContactTearSheetTest.bat
cd RunFiles/CHARDAN
call AddCorporateAccountTest.bat
cd RunFiles/CHARDAN
call GlobalSearchTest.bat
cd RunFiles/CHARDAN
call MyContactsTest.bat
cd RunFiles/CHARDAN
call MyListTest.bat
cd RunFiles/CHARDAN
call RevenueTest.bat
cd RunFiles/CHARDAN
call ReaderShipEmailModule.bat
cd RunFiles/CHARDAN
call ReaderShipModule.bat
cd RunFiles/CHARDAN
call ResearchLibraryModuleTest.bat
cd RunFiles/CHARDAN
cmd /k
