call AccountCoverageManagementTest.bat
cd RunFiles/PIPER
call AccountCoverageManagementTest1.bat
cd RunFiles/PIPER
call AccountCoverageManagementTest2.bat
cd RunFiles/PIPER
call AccountEmailReadership.bat
cd RunFiles/PIPER
call AccountFIFundsTab.bat
cd RunFiles/PIPER
call AccountFundsTab.bat
cd RunFiles/PIPER
call AccountMclaganTab.bat
cd RunFiles/PIPER
call AccountReveneByProduct.bat
cd RunFiles/PIPER
call AccountRevenueByPerson.bat
cd RunFiles/PIPER
call AccountRevenueCurrencyTest.bat
cd RunFiles/PIPER
call AccountTearSheetArchiveTest.bat
cd RunFiles/PIPER
call AccountTearsheetBulkAddContactTest.bat
cd RunFiles/PIPER
call AccountTearsheetBulkEditContactTest.bat
cd RunFiles/PIPER
call AccountTearSheetHeaderVerify.bat
cd RunFiles/PIPER
call AccountTearSheetTest.bat
cd RunFiles/PIPER
call AccountTearSheetTest1.bat
cd RunFiles/PIPER
call AccountTearSheetTest2.bat
cd RunFiles/PIPER
call AccountTearSheetTest3.bat
cd RunFiles/PIPER
call AccountTearSheetTest4.bat
cd RunFiles/PIPER
call AccountTradeSummaryTab.bat
cd RunFiles/PIPER
call ActivityNewlyAddedColumnsVerification.bat
cd RunFiles/PIPER
call ActivityShowFilter.bat
cd RunFiles/PIPER
call ActivityTest.bat
cd RunFiles/PIPER
call AddAccountTest.bat
cd RunFiles/PIPER
call AddContactTest.bat
cd RunFiles/PIPER
call AddCorporateAccountTest.bat
cd RunFiles/PIPER
call AddCorporateAccountTestt.bat
cd RunFiles/PIPER
call AddCoverage.bat
cd RunFiles/PIPER
call AddCoverageFromTickerTearSheet.bat
cd RunFiles/PIPER
call AddCoverageWithSector.bat
cd RunFiles/PIPER
call AddInteractionTest.bat
cd RunFiles/PIPER
call AddInteractionTest1.bat
cd RunFiles/PIPER
call AddInteractionTest2.bat
cd RunFiles/PIPER
call AddInteractionTest3.bat
cd RunFiles/PIPER
call AddInvestorAccountTest.bat
cd RunFiles/PIPER
call AddNewContactTest.bat
cd RunFiles/PIPER
call AddRecommendationTest.bat
cd RunFiles/PIPER
call AddRecommendationTest1.bat
cd RunFiles/PIPER
call AddRecommendationTest2.bat
cd RunFiles/PIPER
call AddServiceAccountTest.bat
cd RunFiles/PIPER
call AddTaskTest.bat
cd RunFiles/PIPER
call AddTestDataUsingApi.bat
cd RunFiles/PIPER
call AnalystTearsheetTest.bat
cd RunFiles/PIPER
call BulkAddContactsTest1.bat
cd RunFiles/PIPER
call BulkAddContactsTest2.bat
cd RunFiles/PIPER
call BulkAddContactsTest3.bat
cd RunFiles/PIPER
call BulkCallTest.bat
cd RunFiles/PIPER
call BulkEmploymentChangeTest.bat
cd RunFiles/PIPER
call BulkMoveTest.bat
cd RunFiles/PIPER
call BulkSubscription.bat
cd RunFiles/PIPER
call CalendarTest.bat
cd RunFiles/PIPER
call ClosedDealsTest.bat
cd RunFiles/PIPER
call ContactRelationshipTest.bat
cd RunFiles/PIPER
call ContactTearSheetHeadersVerify.bat
cd RunFiles/PIPER
call ContactTearSheetTest.bat
cd RunFiles/PIPER
call ContactTearSheetTest1.bat
cd RunFiles/PIPER
call ContactTearSheetTest2.bat
cd RunFiles/PIPER
call ContactTearSheetTest3.bat
cd RunFiles/PIPER
call ContactTearSheetTest4.bat
cd RunFiles/PIPER
call CoverageRequestTest.bat
cd RunFiles/PIPER
call CredOperationMyList.bat
cd RunFiles/PIPER
call CRUD_LogInteraction.bat
cd RunFiles/PIPER
call CustomSubscriptionsTest1.bat
cd RunFiles/PIPER
call CustomSubscriptionsTest2.bat
cd RunFiles/PIPER
call DashboardTest.bat
cd RunFiles/PIPER
call DashboardTest1.bat
cd RunFiles/PIPER
call DashboardTest2.bat
cd RunFiles/PIPER
call DashboardTest3.bat
cd RunFiles/PIPER
call DashboardTest4.bat
cd RunFiles/PIPER
call DashboardVTwoTest.bat
cd RunFiles/PIPER
call DashboradCurrencyTest.bat
cd RunFiles/PIPER
call DealListTest.bat
cd RunFiles/PIPER
call DocumentCriteriaMappingTest.bat
cd RunFiles/PIPER
call EmailEngagementDashboardTest.bat
cd RunFiles/PIPER
call EmailsModuleTest.bat
cd RunFiles/PIPER
call EventManagerTest1.bat
cd RunFiles/PIPER
call EventManagerTest2.bat
cd RunFiles/PIPER
call EventManagerTest3.bat
cd RunFiles/PIPER
call EventManagerTest4.bat
cd RunFiles/PIPER
call FloatingATSTest.bat
cd RunFiles/PIPER
call FloatingCTSTest.bat
cd RunFiles/PIPER
call FloatingCTSTest1.bat
cd RunFiles/PIPER
call FloatingCTSTest2.bat
cd RunFiles/PIPER
call FloatingTTSTest.bat
cd RunFiles/PIPER
call GlobalSearchTest.bat
cd RunFiles/PIPER
call IBAccountTearSheetTest.bat
cd RunFiles/PIPER
call IBActivityTest.bat
cd RunFiles/PIPER
call IBAddInteractionTest1.bat
cd RunFiles/PIPER
call IBAddInteractionTest2.bat
cd RunFiles/PIPER
call IBContactTearsheetTest.bat
cd RunFiles/PIPER
call IBCoverageTest1.bat
cd RunFiles/PIPER
call IBCoverageTest2.bat
cd RunFiles/PIPER
call IBReadershipTest.bat
cd RunFiles/PIPER
call IBReportsTest.bat
cd RunFiles/PIPER
call IBResearchLibraryTest.bat
cd RunFiles/PIPER
call IBServiceAccTSTest.bat
cd RunFiles/PIPER
call IBSummaryTest.bat
cd RunFiles/PIPER
call IBTickerTearSheetTest.bat
cd RunFiles/PIPER
call LibraryPortalTest.bat
cd RunFiles/PIPER
call MarModuleTest.bat
cd RunFiles/PIPER
call MyContactsTest.bat
cd RunFiles/PIPER
call MyListDynamicFiltersTest.bat
cd RunFiles/PIPER
call MyListShareListTest.bat
cd RunFiles/PIPER
call MyListTest.bat
cd RunFiles/PIPER
call MyListTest1.bat
cd RunFiles/PIPER
call MyListTest2.bat
cd RunFiles/PIPER
call MyListTest3.bat
cd RunFiles/PIPER
call NewContactTest.bat
cd RunFiles/PIPER
call OutlookBulkMailTest.bat
cd RunFiles/PIPER
call OutlookSmartSendTest.bat
cd RunFiles/PIPER
call PrismBlastDashboardTest.bat
cd RunFiles/PIPER
call ProcedureSummaryTest.bat
cd RunFiles/PIPER
call ProspectTest.bat
cd RunFiles/PIPER
call QuickLookBulkAddContactsTest1.bat
cd RunFiles/PIPER
call QuickLookBulkAddContactsTest2.bat
cd RunFiles/PIPER
call QuickLookBulkAddContactsTest3.bat
cd RunFiles/PIPER
call ReaderShipEmailModule.bat
cd RunFiles/PIPER
call ReaderShipModule.bat
cd RunFiles/PIPER
call ReaderShipTabShowHideFilter.bat
cd RunFiles/PIPER
call RelationshipEnhancements.bat
cd RunFiles/PIPER
call ReportTest.bat
cd RunFiles/PIPER
call ResearchEntitlementTest.bat
cd RunFiles/PIPER
call ResearchLibraryModuleTest.bat
cd RunFiles/PIPER
call ResearchLibraryTableHeader.bat
cd RunFiles/PIPER
call ResearchSalesPeronTearsheet.bat
cd RunFiles/PIPER
call ResearchSalesTSRevenueCurrencyTest.bat
cd RunFiles/PIPER
call ResearchSubscriptionVTest1.bat
cd RunFiles/PIPER
call ResearchSubscriptionVTest2.bat
cd RunFiles/PIPER
call RevenueAdvancedAllTableHeaders.bat
cd RunFiles/PIPER
call RevenueAdvancedTest.bat
cd RunFiles/PIPER
call RevenueAdvancedTest1.bat
cd RunFiles/PIPER
call RevenueAdvancedTest2.bat
cd RunFiles/PIPER
call RevenueCurrencyTest.bat
cd RunFiles/PIPER
call RevenueModule.bat
cd RunFiles/PIPER
call RevenueTableExample.bat
cd RunFiles/PIPER
call RevenueTest.bat
cd RunFiles/PIPER
call RevenueTest1.bat
cd RunFiles/PIPER
call RevenueTest2.bat
cd RunFiles/PIPER
call RevenueVTwoTest.bat
cd RunFiles/PIPER
call ROITest.bat
cd RunFiles/PIPER
call RoleNavigationTest.bat
cd RunFiles/PIPER
call SalesTraderTearSheetTest.bat
cd RunFiles/PIPER
call SalesTraderTSRevenueCurrencyTest.bat
cd RunFiles/PIPER
call ServiceAccountTearsheetBulkAddContactTest.bat
cd RunFiles/PIPER
call ServiceAccountTearsheetBulkEditTest.bat
cd RunFiles/PIPER
call ServiceAccountTest.bat
cd RunFiles/PIPER
call ServiceAccountTest1.bat
cd RunFiles/PIPER
call ServiceAccountTest2.bat
cd RunFiles/PIPER
call ShowHideFilterForEmailReaderShipAndReadershipTab.bat
cd RunFiles/PIPER
call SponserCompaniesTab.bat
cd RunFiles/PIPER
call SuperAccountBulkEditTest.bat
cd RunFiles/PIPER
call SuperAccountTest.bat
cd RunFiles/PIPER
call TickerCoverageManagementTest.bat
cd RunFiles/PIPER
call TickerCoverageManagementTest1.bat
cd RunFiles/PIPER
call TickerCoverageManagementTest2.bat
cd RunFiles/PIPER
call TickerTearsheetBulkAddContactTest.bat
cd RunFiles/PIPER
call TickerTearsheetBulkEditContactTest.bat
cd RunFiles/PIPER
call TickerTearSheetTest.bat
cd RunFiles/PIPER
call TickerTearSheetTest1.bat
cd RunFiles/PIPER
call TickerTearSheetTest2.bat
cd RunFiles/PIPER
call TickerTearSheetTest3.bat
cd RunFiles/PIPER
call TickerTearSheetTest4.bat
cd RunFiles/PIPER
call TopResearchSalesPerson.bat
cd RunFiles/PIPER
call TopSalesTradersGrossComm.bat
cd RunFiles/PIPER
call TradesModule.bat
cd RunFiles/PIPER
call UnsubscribeRequestsTest.bat
cmd /k
