call AccountCoverageManagementTest.bat
cd RunFiles/ROSENBLATT
call AccountTearSheetArchiveTest.bat
cd RunFiles/ROSENBLATT
call AccountTearSheetTest.bat
cd RunFiles/ROSENBLATT
call ActivityShowFilter.bat
cd RunFiles/ROSENBLATT
call ActivityTest.bat
cd RunFiles/ROSENBLATT
call AddContactTest.bat
cd RunFiles/ROSENBLATT
call AddCorporateAccountTest.bat
cd RunFiles/ROSENBLATT
call AddCoverage.bat
cd RunFiles/ROSENBLATT
call AddCoverageFromTickerTearSheet.bat
cd RunFiles/ROSENBLATT
call AddCoverageWithSector.bat
cd RunFiles/ROSENBLATT
call AddInteractionTest.bat
cd RunFiles/ROSENBLATT
call AddInvestorAccountTest.bat
cd RunFiles/ROSENBLATT
call AddNewContactTest.bat
cd RunFiles/ROSENBLATT
call AddRecommendationTest.bat
cd RunFiles/ROSENBLATT
call AddServiceAccountTest.bat
cd RunFiles/ROSENBLATT
call BulkCallTest.bat
cd RunFiles/ROSENBLATT
call BulkEmploymentChangeTest.bat
cd RunFiles/ROSENBLATT
call BulkSubscription.bat
cd RunFiles/ROSENBLATT
call ContactRelationshipTest.bat
cd RunFiles/ROSENBLATT
call ContactTearSheetHeadersVerify.bat
cd RunFiles/ROSENBLATT
call ContactTearSheetTest.bat
cd RunFiles/ROSENBLATT
call DashboardTest.bat
cd RunFiles/ROSENBLATT
call FloatingATSTest.bat
cd RunFiles/ROSENBLATT
call FloatingCTSTest.bat
cd RunFiles/ROSENBLATT
call GlobalSearchTest.bat
cd RunFiles/ROSENBLATT
call MyContactsTest.bat
cd RunFiles/ROSENBLATT
call MyListTest.bat
cd RunFiles/ROSENBLATT
call NewContactTest.bat
cd RunFiles/ROSENBLATT
call ReaderShipEmailModule.bat
cd RunFiles/ROSENBLATT
call ReaderShipModule.bat
cd RunFiles/ROSENBLATT
call ReportTest.bat
cd RunFiles/ROSENBLATT
call ResearchLibraryModuleTest.bat
cd RunFiles/ROSENBLATT
call ResearchSalesPeronTearsheet.bat
cd RunFiles/ROSENBLATT
call RevenueAdvancedTest.bat
cd RunFiles/ROSENBLATT
call RevenueModule.bat
cd RunFiles/ROSENBLATT
call RevenueTableExample.bat
cd RunFiles/ROSENBLATT
call RevenueTest.bat
cd RunFiles/ROSENBLATT
call SalesTraderTearSheetTest.bat
cd RunFiles/ROSENBLATT
call ServiceAccountTest.bat
cd RunFiles/ROSENBLATT
call SponserCompaniesTab.bat
cd RunFiles/ROSENBLATT
call SuperAccountTest.bat
cd RunFiles/ROSENBLATT
call TickerCoverageManagementTest.bat
cd RunFiles/ROSENBLATT
call TickerTearSheetTest.bat
cd RunFiles/ROSENBLATT
call TopResearchSalesPerson.bat
cd RunFiles/ROSENBLATT
call TopSalesTradersGrossComm.bat
cd RunFiles/ROSENBLATT
call TradesModule.bat
cmd /k
