Prism_AccountCoverage= AC_C_1

Toastmessage:
AC_C_1_toast_msg=Updates to Prism are available. Would you like to update? 
AC_C_1_toast_msg_Click_ok=//button[@class='btn btn-custom chk']
AC_C_1_toast_Close=//button[@class='toast-close-button']

AC_C_1_table_rowcount =//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer DTFC_Cloned']//tbody//tr
AC_C_1_table_AccountName=(//th[text()='Account Name'])[2]
AC_C_1_table_row1=//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer DTFC_Cloned']//tbody//tr[temp]//td[1]
AC_C_1_RevenueBackClick=//ol[@id='prism_page_title']//a[1]

DashBoardModule=//li[@data-module='Dashboard']
RevenueModule     = //li[@data-module='Revenue']/a[@class='menuWithSub']
RevenueSubModule  =//li[@data-module='Revenue']/ul/li[2]/a
ActivityModule=//li[@data-module='Activity']/a[@class='menuWithSub']
ActivitySubModule=//li[@data-module='Activity']/ul/li[2]/a
AC_C_1_CoverageTable=//*[@data-fixedid='tcaccountcoveragetable']







RevenueByPerson:
AC_C_1_Revenuebyperson_tab=//a[@data-tabid='tab-person']
AC_C_1_Account_CloseBtn=//button[@title='Close']
AC_C_1_Rv_Per_AccountCove_Header=(//th[@data-fixedid='tcrevacc_covered'])[2]
AC_C_1_Rv_Per_table_row1=//td[contains(@class,'dt-right acct_conrg_chld')][temp]
AC_C_1_Rv_Person_SearchField=(//input[@placeholder='Search...'])[2]
AC_C_1_Rv_Person_Account_CoverageClick=//div[@class='dataTables_scrollBody']//table[@data-fixedid='tcrevenuebypersontabledata']//tbody//tr//td[7]//a
AC_C_1_Rv_Person_AccountPage=//div[@id='pie_drill']
AC_C_1_Rv_Person_AccountSerchField=(//input[@placeholder='Search...'])[3]
AC_C_1_Rv_Person_AccountPage=//div[@id='pie_drill']
AC_C_1_Rv_Person_AccountrowCount=//table[@data-fixedid='tcrevenuebypersonacccoveredcounttabledata']//tbody//tr
AC_C_1_Rv_Person_AccountName=//table[@data-fixedid='tcrevenuebypersonacccoveredcounttabledata']//tbody//tr//td[1]//a
AC_C_1_Rv_Person_AccountSheet_Close=//div[@id='pie_drill']//button[@class='close']


ReavenueByAccount:
AC_C_1_Rv_Account_Search=//input[@placeholder='Search...']
AC_C_1_Rv_Account_Header=//div[@class='dataTables_wrapper form-inline dt-bootstrap no-footer dts DTS']//div[@class='dataTables_scrollHeadInner']//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//tr[3]//th[@data-fixedid='tcrevcoverage']
AC_C_1_Rv_Account_HeaderScroll=//div[@class='dataTables_wrapper form-inline dt-bootstrap no-footer dts DTS']//div[@class='dataTables_scrollHeadInner']//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//tr[3]//th[@data-fixedid='delta']
AC_C_1_Rv_Account_HeaderScroll1=//div[@class='dataTables_wrapper form-inline dt-bootstrap no-footer dts DTS']//div[@class='dataTables_scrollHeadInner']//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//tr[3]//th[@data-fixedid='cur_ann']
AC_C_1_Rv_Account_HeaderScroll2=//div[@class='dataTables_wrapper form-inline dt-bootstrap no-footer dts DTS']//div[@class='dataTables_scrollHeadInner']//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//tr[3]//th[text()='Mkt. Wallet']
AC_C_1_Rv_Account_HeaderexpandClickk=//div[@class='dataTables_scrollHeadInner']//i[@data-childcols='[28,29,30,31,32,33]']


AC_C_1_Rv_Account_CoverageCount_Row=//div[@class='dataTables_scrollBody']//table[@data-fixedid='tcrevenuebyaccounttabledata']//tbody//tr
//AC_C_1_Rv_Account_CoverageCount=//table[@data-fixedid='tcrevenuebyaccounttabledata']//tbody//td[29]
AC_C_1_Rv_Account_CoverageCountHead=//div[@class='dataTables_scrollHead']//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//thead//th
AC_C_1_Rv_Account_CoverageHeadText=//div[@class='dataTables_scrollHead']//table[@class='compact table cell-border table-bordered custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//thead//th[text()='#Coverage']
//AC_C_1_Rv_Account_Coverageindex_position=//table[@data-fixedid='tcrevenuebyaccounttabledata']//tbody//tr[Acc_count]//td[Index_Acc]
AC_C_1_Rv_Account_Coverageindex=//table[@data-fixedid='tcrevenuebyaccounttabledata']//tbody//tr[1]//td[8]
AC_C_1_Rv_Account_Cov_count_page=(//div[@class='modal-header bg-primaryLight'])[2]
AC_C_1_Rv_Account_CoverageCount_Click=//table[@data-fixedid='tcrevenuebyaccounttabledata']//tbody//tr[1]//td[8]//a

AC_C_1_Rv_CoverageCount_RowCount=//table[@data-fixedid='tcrevenuebyaccountcoveragecounttabledata']//tbody//tr

AC_C_1_Rv_CoverageCount_HeaderCount=//div[@class='dataTables_scrollHeadInner']//table[@class='compact table table-bordered table-striped theme-table custDataTable nowrap dataTable']//thead//th
AC_C_1_Rv_CoverageCount_SalesPerson=//div[@class='dataTables_scrollHeadInner']//table[@class='compact table table-bordered table-striped theme-table custDataTable nowrap dataTable']//thead//th[text()='Sales Person Name']
AC_C_1_Rv_CoverageCount_SalesPerson_position=//table[@data-fixedid='tcrevenuebyaccountcoveragecounttabledata']//tbody//tr[Cov_count]//td[index_Cov]

AC_C_1_Rv_CoverageCount_Close_Btn=//button[@id='rev_acc_drill_table_pop_up_close']//span[1]






CoverageTab
AC_C_1_CoverageTab_click=(//a[@data-pageplugin='autoflow'])[3]
AC_C_1_CoverageTab_Table=//*[@data-fixedid='tcaccountcoveragetabledata']



//AC_C_1_CoverageTab_Tablerow_Headercount=//table[@data-fixedid='tcaccountcoveragetabledata']//thead//tr[1]//td
//AC_C_1_CoverageTab_Tablerow_Header=//table[@data-fixedid='tcaccountcoveragetabledata']//thead//tr[1]//td[temp]
AC_C_1_CoverageTable_Region=//table[@data-fixedid='tcaccountcoveragetabledata']//tr//td[text()='Region']

//table[@data-fixedid='tcaccountcoveragetabledata']//tr[2]//td






ValidateMsg:
AC_C_1_CoverageTab_ExpandClick=(//table[@data-fixedid='tcaccountcoveragetabledata']//td[@class='collapse_head toggleHead'])[1]/span
AC_C_1_Expand_Down=pull-right fa tab fa-caret-down ,



DashBoard
AC_C_1_DashB_Top=//a[@data-tabid='tab-top-clnt']
AC_C_1_DashB_SalesHeader=//th[text()='Sales Coverage']
AC_C_1_DashB_Search=//div[@id='dataTable_topten_client_collapsed_filter']//input[@placeholder='Search...']
AC_C_1_DashB_Icon=//span[@id='page_panel_icon']
EditAccount
AC_C_1_Action_MenuClick=//i[@title='Actions']
AC_C_1_Edit_AccoClick=//li[@class='edit_account_crm']//a[1]
AC_C_1_Edit_Accopage=//h4[text()='Edit Account']
AC_C_1_Edit_Acco_legalname=//input[@id='Investor_accountInfo_accountLegalName']
AC_C_1_AccoCoverage_Tab=//a[@data-tabid='Investor_accountCoverage']
AC_C_1_Edit_Acc_CoverageTable=//table[@id='table-Investor_accountCoverage_accountCoverageTable']
AC_C_1_Edit_Acc_Close=//div[@id='add-account']/div[1]/div[1]/div[1]/button[1]
AC_C_1_Edit_Acc_Confirm_Close=//button[@id='close_ok']
AC_C_1_Edit_Acc_TableHeaderCount=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th
AC_C_1_Edit_Acc_TablerowCount=//div[@class='dataTables_scrollBody']//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tbody//tr
AC_C_1_Edit_Acc_TablerowCount1=//div[@class='dataTables_scrollBody']//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tbody//tr[temp]


AC_C_1_Edit_Acc_Table_Emp_Name=//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tr[temp]//td[index]
AC_C_1_Edit_Acc_Table_Role=//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tr[temp]//td[index]
AC_C_1_Edit_Acc_Table_Business_Line=//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tr[temp]//td[index]
AC_C_1_Edit_Acc_Table_Product=//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tr[temp]//td[index]
AC_C_1_Edit_Acc_Table_Coverage_type=//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tr[temp]//td[index]
AC_C_1_Edit_Acc_TableStatuscolumn=//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tr[temp]//td[index]



AC_C_1_Edit_Acc_Emp_name=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th[text()='Employee Name']
AC_C_1_Edit_Acc_Role=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th[text()='Role']
AC_C_1_Edit_Acc_Businessline=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th[text()='Business Line']
AC_C_1_Edit_Acc_product=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th[text()='Product']
AC_C_1_Edit_Acc_Coveragetype=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th[text()='Coverage Type']
AC_C_1_Edit_Acc_Status=//div[@class='dataTables_scrollHeadInner']//table[@class='table table-bordered theme-table custDataTable display nowrap dataTable no-footer']//th[text()='Status']


AC_C_1_CoverageTab_TableHeaderCount=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//thead//tr//td
AC_C_1_CoverageTab_TablerowCount=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr
//AC_C_1_CoverageTab_TablerowCount1=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr[rowtemp]


AC_C_1_CoverageTable_ProductName=//table[@data-fixedid='tcaccountcoveragetabledata']//tr//td[text()='Product Name']
AC_C_1_CoverageTable_Pers_name=//table[@data-fixedid='tcaccountcoveragetabledata']//tr//td[text()='Person Name']
AC_C_1_CoverageTable_Job_Func=//table[@data-fixedid='tcaccountcoveragetabledata']//tr//td[text()='Job Function']
AC_C_1_CoverageTable_Acc_Covetype=//table[@data-fixedid='tcaccountcoveragetabledata']//tr//td[text()='Account Coverage Type']
AC_C_1_CoverageTable_Busi_unit=//table[@data-fixedid='tcaccountcoveragetabledata']//tr//td[text()='Business Unit']

AC_C_1_CoverageTab_product=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr[row]//td[index_pos]
AC_C_1_CoverageTab_E_personname=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr[row]//td[index_pos]
AC_C_1_CoverageTab_R_job_func=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr[row]//td[index_pos]
AC_C_1_CoverageTab_Coveragetype=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr[row]//td[index_pos]
AC_C_1_CoverageTab_Business_unit=//div[@class='table-responsive']//table[@data-fixedid='tcaccountcoveragetabledata']//tbody//tr[row]//td[index_pos]

Activity:
AC_C_1_Activity_Search=//input[@placeholder='Search...']
AC_C_1_Activity_RowCount=//table[@data-fixedid='tcactivitytabledata']//tbody//tr

AC_C_1_Activity_HeaderCount=//div[@class='dataTables_scrollHeadInner']//table[@data-fixedid='tcactivitytabledata']//thead//th
AC_C_1_Activity_SalesPerson=//div[@class='dataTables_scrollHeadInner']//table[@data-fixedid='tcactivitytabledata']//thead//th[@data-fixedid='salesTeam']
AC_C_1_Activity_SalesPerson_position=//table[@data-fixedid='tcactivitytabledata']//tbody//tr[Ac_row]//td[index_posi]

AC_C_1_Activity_yearFilter_Click=//i[contains(@class,'fa fa-calendar-o')]
AC_C_1_Activity_year_2021_Click=//body/div[@class='daterangepicker dropdown-menu ltr opensleft'][2]//div[@class='ranges']/ul/li[@data-range-key='YTD 2021']






