AccountCreation = AC_1_1
	Account_Creation_Web_Element:
		AC_1_id_Add_icon 			=	header_action_button_icon
		AC_1_id_Add_accounts		=	headerAddAccount
		AC_1_id_AccCreation_Page	=	add-account
		AC_1_id_AccType_Count		=	//*[@class='newacc-content']//div//input
		AC_1_id_AccType_Name		=	//*[@class='newacc-content']//div[temp]//span
		AC_1_id_AccCreTabCount		=	//*[contains(@class,'temp')]//ul[contains(@class,'acctCreationtabs')]//li
		AC_1_id_AccCreTabName		=	//*[contains(@class,'temp')]//ul[contains(@class,'acctCreationtabs')]//li[index]/a
		AC_1_id_AccFullWidth		=	//div[@class='panel-form create-new-acc full-width']
		AC_1_id_AccSaveButton		=	save-account
		AC_1_id_AccSaveSubmit		=	sumbit_ok
		AC_1_id_Panelhead			=	panelHeadTab
		AC_1_id_BurgerEditButton	=	//div[@id='page-wrapper']//i[@data-toggle='dropdown']
		AC_1_id_EditButton			=	//li[@id='editAccountCrm']
		AC_1_id_TickerEditButton	=	//li[@id='editTickerAccountCrm']
		AC_1_id_EditPage			=	//h4[@id='myModalLabel'and contains(text(),'Edit Account')]
		AC_1_id_EditCloseButton		=	//div[@id='add-account']//button[@class='close']
		AC_1_id_closeOkButton		=	//button[@id='close_ok']
		AC_1_id_AccountCloseButton	=	//*[@id='panelHeadTab']/li[1]/button
		AC_1_id_AccountPage			=	//div[@id='page-wrapper']
		AC_1_id_GlobalSearch		=	top-search
		AC_1_id_AccountSearchList	=	(//div[@id='wrapper']//div[@class='typeahead-result globalSettingResult']//li/a)[1]
		AC_1_id_filter_count_List	=	//*[@class='filter-check-area']//div
		AC_1_id_filter_Selected_check	=	//*[@class='filter-check-area']//div[temp]/input
		AC_1_id_filter_deselect		=	//*[@class='filter-check-area']//div[temp]/label
		AC_1_id_Ticker_Filter		=	//label[@title='Ticker']
		AC_1_id_CoveredAccFilter	=	//label[@title='Covered Accounts']
		AC_1_id_ProspectAccFilter	=	//label[@title='Prospects']
		AC_1_id_AccListDisplayed	=	//div[@class='typeahead-result globalSettingResult']//li[@class='typeahead-item']
		AC_1_id_AccNameDisplayedSel	=	//div[@class='typeahead-result globalSettingResult']//li[@class='typeahead-item'][temp]//span
		
		Tear_Sheet:
		AC_1_id_AccAddress			=	accAddress
		AC_1_id_TkrAccAddress		=	corAccAddress
		AC_1_id_TkrName				=	tick_nme
		AC_1_id_AccName				=	//*[@id='search_header_slide']//span[@class='search_slider_title m-r-sm font-md']
		AC_1_id_AccPhNo				=	accPhoneNo
		AC_1_id_AccAltPhNo			=	accAltPhoneNo
		AC_1_id_TkrAccPhNo			=	corAccPhoneNo
		AC_1_id_TkrAccAltPhNo		=	corAccAltPhoneNo
		AC_1_id_ParentAcc			=	//div[@id='search_header_slide']//div[@class='parent_acct orgName ']/span/a
		
		Tab_Click:
		AC_1_id_Account_Info				=	//*[@data-tabid	='temp_accountInfo']
		AC_1_id_Office_Details				=	//*[@data-tabid	='temp_officeDetails']
		AC_1_id_ThirdPartyDetails			=	//*[@data-tabid	='temp_thirdPartyDetails']
		AC_1_id_MIFIDId						=	//*[@data-tabid	='temp_mifidMapping']
		AC_1_id_AccountCoverage				=	//*[@data-tabid	='temp_accountCoverage']
		AC_1_id_AccountBioTab				=	//*[@data-tabid	='temp_accountBio']
		AC_1_id_InvestmentFocusDetailsTab	=	//*[@data-tabid	='temp_investmentFocusDetails']
		
		Account_Info:
		AC_1_id_AccLegal_Name		=	temp_accountInfo_accountLegalName
		AC_1_id_Common_Name			=	temp_accountInfo_commonName
		AC_1_id_AccountStage		=	temp_accountInfo_accountStage
		AC_1_id_InvestorType		=	temp_accountInfo_investorType
		AC_1_id_InvestorSubType		=	temp_accountInfo_investorSubType
		AC_1_id_CustomInvestorType	=	temp_accountInfo_customInvestorType
		AC_1_id_OwnershipStatus		=	temp_accountInfo_ownershipStatus
		AC_1_id_TickerSymbol		=	temp_accountInfo_tickerSymbol
		AC_1_id_AccShortName		=	temp_accountInfo_accountShortCode
		AC_1_id_Website				=	temp_accountInfo_website
		AC_1_id_AccTier				=	temp_accountInfo_accountTier
		AC_1_id_AccRegion			=	temp_accountInfo_accountRegion
		AC_1_id_PartOfASuperAcc		=	temp_accountInfo_partOfAParentAccount
		AC_1_id_BusinessRegion		=	temp_accountInfo_firmBusinessRegion
		AC_1_id_EmailDomain			=	temp_accountInfo_emailDomain
		AC_1_id_FixedLineConn		=	temp_accountInfo_fixedLineConnection
		AC_1_id_AppTradingAcc		=	temp_accountInfo_approvedTradingAccount
		AC_1_id_RetentionStock		=	temp_accountInfo_retentionStock
		AC_1_id_ConsumptionReport	=	temp_accountInfo_consumptionReport_chosen
		AC_1_id_McLaganTarget$		=	temp_accountInfo_mclaganTarget
		AC_1_id_AnnuGoal$			=	temp_accountInfo_commissionTarget
		AC_1_id_OwnershipStruc		=	temp_accountInfo_ownershipStructure
		AC_1_id_SovereignEntity		=	temp_accountInfo_sovereignEntity
		AC_1_id_Sector				=	temp_accountInfo_sector
		AC_1_id_SubSector			=	temp_accountInfo_subSector
		AC_1_id_EmailDomain			=	temp_accountInfo_emailDomain
		AC_1_id_GeneralNotes		=	temp_accountInfo_notes
		
		Office_Details:
		AC_1_id_StreetAddress1		=	temp_officeDetails_streetAddress1
		AC_1_id_StreetAddress2		=	temp_officeDetails_streetAddress2
		AC_1_id_City				=	temp_officeDetails_city
		AC_1_id_State/County		=	temp_officeDetails_stateCountry
		AC_1_id_Country				=	temp_officeDetails_country
		AC_1_id_Zip/PostalCode		=	temp_officeDetails_zipPostalCode
		Ac_1_id_PhoneNoCode			=	//label[@for='temp_officeDetails_phoneNo']/following-sibling::div[@class='add-set']//div[@class='selected-flag']
		Ac_1_id_PNCountryCodeList	=	//label[@for='temp_officeDetails_phoneNo']/following-sibling::div[@class='add-set']//ul[contains(@class,'country-list')]//li
		AC_1_id_PhoneNo.			=	temp_officeDetails_phoneNo
		Ac_1_id_AltPhoneNoCode		=	//label[@for='temp_officeDetails_alternatePhoneNo']/following-sibling::div[@class='add-set']//div[@class='selected-flag']
		Ac_1_id_APNCountryCodeList	=	//label[@for='temp_officeDetails_alternatePhoneNo']/following-sibling::div[@class='add-set']//ul[contains(@class,'country-list')]//li
		AC_1_id_AlternatePhoneNo.	=	temp_officeDetails_alternatePhoneNo
		AC_1_id_FaxNoCode			=	//label[@for='temp_officeDetails_faxNo']/following-sibling::div[@class='add-set']//div[@class='selected-flag']
		Ac_1_id_FaxCountryCodeList	=	//label[@for='temp_officeDetails_faxNo']/following-sibling::div[@class='add-set']//ul[contains(@class,'country-list')]//li
		AC_1_id_FaxNo.				=	temp_officeDetails_faxNo
		AC_1_id_ClosestAirport		=	temp_officeDetails_closestAirport
		AC_1_id_HeadQuarter			=	temp_officeDetails_headQuarter
		AC_1_id_MiFIDcompliant		=	temp_officeDetails_mifidCompliant
		AC_1_id_MiFIDRegion			=	temp_officeDetails_mifIdRegion
		
		
		Office_Details_Table:
		AC_1_id_TableOffice			=	//*[@colheadname='office'][1]
		AC_1_id_TableAddress		=	//*[@colheadname='streetAddress1'][1]
		AC_1_id_TableCity			=	//*[@colheadname='city'][1]
		AC_1_id_TableState			=	//*[@colheadname='stateCountry'][1]
		AC_1_id_TableCountry		=	//*[@colheadname='country'][1]
		AC_1_id_TableZip			=	//*[@colheadname='zipPostalCode'][1]
		AC_1_id_TablePhoneNo		=	//*[@colheadname='phoneNo'][1]
		AC_1_id_TableAltPhoneNo		=	//*[@colheadname='alternatePhoneNo'][1]
		AC_1_id_TableFax			=	//*[@colheadname='faxNo'][1]
		AC_1_id_OffTable			=	temp_officeDetails_officeDetailsTable
		
		Account_Bio:
		AC_1_id_AccountBio			=	temp_accountBio_bio
		AC_1_id_InvestmentApproach	=	temp_accountBio_investmentStyle
		AC_1_id_Tags				=	temp_accountBio_tagssearch
		
		Third_Party_Details:
		AC_1_id_FirmAccountID			=	temp_thirdPartyDetails_firmAccountId
		AC_1_id_LegalEntityID(LEI)		=	temp_thirdPartyDetails_legalEntityId
		AC_1_id_CIK						=	temp_thirdPartyDetails_cik
		AC_1_id_CRDID					=	temp_thirdPartyDetails_crdId
		AC_1_id_iPreoID					=	temp_thirdPartyDetails_iPreoId
		AC_1_id_IRSNo.					=	temp_thirdPartyDetails_irsNo
		AC_1_id_CapIQID					=	temp_thirdPartyDetails_capIqId
		AC_1_id_BloombergAccountID		=	temp_thirdPartyDetails_bloombergAccountId
		AC_1_id_ThomsonReutersAccountID	=	temp_thirdPartyDetails_thomsonReutersAccountId
		AC_1_id_CUSIPNo.				=	temp_thirdPartyDetails_cusipNo
		AC_1_id_SEDOLNo.				=	temp_thirdPartyDetails_sedolNo
		AC_1_id_ISIN					=	temp_thirdPartyDetails_isin
		AC_1_id_BloombergSecurityID		=	temp_thirdPartyDetails_bloombergSecurityId
		AC_1_id_BloombergFIGIID			=	temp_thirdPartyDetails_bloombergFigiId
		AC_1_id_BusinessUnit			=	temp_thirdPartyDetails_businessunit
		AC_1_id_SendtoIntegration		=	temp_thirdPartyDetails_sendtointegration
		
		MIFIDId_Details:
		AC_1_id_AreaAndCountry			=	(//div[@id='Investor_mifid_accordion']//td[@class='panel-title'])[1]
		AC_1_id_Address1&2				=	(//div[@id='Investor_mifid_accordion']//td[@class='panel-title'])[2]
		AC_1_id_MIFIDIdRegion			=	(//div[@id='Investor_mifid_accordion']//td[@class='panel-title'])[3]
		AC_1_id_Contact					=	(//div[@id='Investor_mifid_accordion']//td[@class='panel-title'])[4]
		
		
		Account_Coverage:
		AC_1_id_EmployeeName		=	temp_accountCoverage_employeeName
		AC_1_id_Role				=	temp_accountCoverage_role
		AC_1_id_RRCode				=	temp_accountCoverage_rrCode
		AC_1_id_Region				=	temp_accountCoverage_region
		AC_1_id_BusinessLine		=	temp_accountCoverage_businessLine
		AC_1_id_Product				=	temp_accountCoverage_product
		AC_1_id_Coveragestartdate	=	temp_accountCoverage_coverageStartDate	
		AC_1_id_Coverageenddate		=	temp_accountCoverage_coverageEndDate
		AC_1_id_Coveragetype		=	temp_accountCoverage_coverageType
		AC_1_id_Coverage%			=	temp_accountCoverage_coveragePercentage
		AC_1_id_Status				=	temp_accountCoverage_status
		AC_1_id_Confidential		=	temp_accountCoverage_confidential
		AC_1_id_EmployeeNameSelect  =   //li[@class='typeahead-item']//descendant::small[contains(text(),'temp')]
		
		Account_Coverage_Table:
		AC_1_id_TableEmployeeName		=	(//*[@colheadname='employeeName.name'])[1]
		AC_1_id_TableRole				=	(//*[@colheadname='role'])[1]
		AC_1_id_TableRegion				=	(//*[@colheadname='region'])[1]
		AC_1_id_TableRRCode				=	(//*[@colheadname='rrCode'])[1]
		AC_1_id_TableBussinessLine		=	(//*[@colheadname='businessLine'])[1]
		AC_1_id_TableProduct			=	(//*[@colheadname='product'])[1]
		AC_1_id_TableCoverageType		=	(//*[@colheadname='coverageType'])[1]
		AC_1_id_TableCoverageStartDate	=	//*[@id='table-Investor_accountCoverage_accountCoverageTable_wrapper']//table[@id='table-Investor_accountCoverage_accountCoverageTable']//tbody//tr[1]//td[7]
		AC_1_id_TableValues				=	//table[@id='table-temp_accountCoverage_accountCoverageTable']
		AC_1_id_AccCovTable				=	temp_accountCoverage_accountCoverageTable
		
		
		Investment_Focus_Details:
		AC_1_id_DominantInvestmentStyle			=	temp_investmentFocusDetails_dominantInvestmentStyle_chosen
		AC_1_id_InvestmentOrientation			=	temp_investmentFocusDetails_investmentOrientation_chosen
		AC_1_id_TypeofInvestment				=	temp_investmentFocusDetails_typeOfInvestment
		AC_1_id_SizeofInvestment				=	temp_investmentFocusDetails_sizeOfInvestment
		AC_1_id_PreferredInvestmentSector		=	temp_investmentFocusDetails_preferredInvestmentsector_chosen
		AC_1_id_PreferredInvestmentSub-Sector	=	temp_investmentFocusDetails_preferredInvestmentSubSector_chosen
		AC_1_id_PreferredInvestmentLocation		=	temp_investmentFocusDetails_preferredInvestmentlocation_chosen
		AC_1_id_PreferredMarketCap				=	temp_investmentFocusDetails_preferredMarketCap_chosen
		AC_1_id_PreferredCompanyMetrics			=	temp_investmentFocusDetails_preferredCompanyMetrics
		
		
		
	Account_Creation_Values:
		AC_1_v_case_from_excel		= 	1
		AC_1_v_testCasePath 		= 	\\TestCases\\AccountCreation\\AC_1.xlsx
		AC_1_v_VerifyTestPath		=	\\TestCases\\AccountCreation\\AV_1.xlsx
		AC_1_v_rowid				=	Row Id
		AC_1_v_AccType				=	AccType
		AC_1_v_AccNameSearch		=	AccNameSearch
		AC_1_v_AccName				=	AccName
		
		
		Account_Info:
		AC_1_v_AccType				=	AccType
		AC_1_v_AccLegalName			=	AccountLegalName
		AC_1_v_CommonName			=	CommonName
		AC_1_v_AccountStage			=	AccountStage
		AC_1_v_InvestorType			=	InvestorType
		AC_1_v_InvestorSubType		=	InvestorSubType
		AC_1_v_CustomInvestorType	=	CustomInvestorType
		AC_1_v_OwnershipStatus		=	OwnershipStatus
		AC_1_v_TickerSymbol			=	TickerSymbol
		AC_1_v_AccShortName			=	AccShortName
		AC_1_v_Website				=	Website
		AC_1_v_AccTier				=	AccTier
		AC_1_v_AccRegion			=	AccRegion
		AC_1_v-PartOfASuperAccNS	=	PartOfASprAccNS
		AC_1_v_PartOfASuperAcc		=	PartOfASuperAcc
		AC_1_v_BusinessRegion		=	BusinessRegion
		AC_1_v_EmailDomain			=	EmailDomain
		AC_1_v_FixedLineConn		=	FixedLineConn
		AC_1_v_AppTradingAcc		=	AppTradingAcc
		AC_1_v_RetentionStock		=	RetentionStock
		AC_1_v_ConsumptionReport	=	ConsumptionReport
		AC_1_v_McLaganTarget$		=	McLaganTarget$
		AC_1_v_AnnuGoal$			=	AnnuGoal$
		AC_1_v_OwnershipStruc		=	OwnershipStruc
		AC_1_v_SovereignEntity		=	SovereignEntity
		AC_1_v_Sector				=	Sector
		AC_1_v_SubSector			=	SubSector
		AC_1_v_EmailDomain			=	EmailDomain
		AC_1_v_GeneralNotes			=	GeneralNotes
		
		Office_Details:
		AC_1_v_StreetAddress1		=	StreetAddress1
		AC_1_v_StreetAddress2		=	StreetAddress2
		AC_1_v_City					=	City
		AC_1_v_State/County			=	State/County
		AC_1_v_Country				=	Country
		AC_1_v_Zip/PostalCode		=	Zip/PostalCode
		AC_1_v_PNCountryCode		=	PNCountryCode
		AC_1_v_PhoneNo.				=	PhoneNo.
		AC_1_v_APNCountryCode		=	APNCountryCode
		AC_1_v_AlternatePhoneNo.	=	AlternatePhoneNo.
		AC_1_v_FaxCountryCode		=	FaxCountryCode
		AC_1_v_FaxNo.				=	FaxNo.
		AC_1_v_ClosestAirport		=	ClosestAirport
		AC_1_v_HeadQuarter			=	HeadQuarter
		AC_1_v_MiFIDcompliant		=	MiFIDcompliant
		AC_1_v_MiFIDRegion			=	MiFIDRegion
		
		Account_Bio: 
		AC_1_v_AccountBio			=	AccountBio
		AC_1_v_InvestmentApproach	=	InvestmentApproach
		AC_1_v_TagsSuggestion		=	TagSugg
		AC_1_v_Tags					=	Tags
		
		Third_Party_Details:
		AC_1_v_FirmAccountID			=	FirmAccountID
		AC_1_v_LegalEntityID(LEI)		=	LegalEntityID(LEI)
		AC_1_v_CIK						=	CIK
		AC_1_v_CRDID					=	CRDID
		AC_1_v_iPreoID					=	iPreoID
		AC_1_v_IRSNo.					=	IRSNo.
		AC_1_v_CapIQID					=	CapIQID
		AC_1_v_BloombergAccountID		=	BloombergAccountID
		AC_1_v_ThomsonReutersAccountID	=	ThomsonReutersAccountID
		AC_1_v_CUSIPNo.					=	CUSIPNo.
		AC_1_v_SEDOLNo.					=	SEDOLNo.
		AC_1_v_ISIN						=	ISIN
		AC_1_v_BloombergSecurityID		=	BloombergSecurityID
		AC_1_v_BloombergFIGIID			=	BloombergFIGIID
		AC_1_v_BusinessUnit				=	BusinessUnit
		AC_1_v_SendtoIntegration		=	SendtoIntegration
		
		Account_Coverage:
		AC_1_v_EmployeeName			=	EmployeeName
		AC_1_v_EmployeeEmailId		=	EmployeeEmailId
		AC_1_v_Role					=	Role
		AC_1_v_RRCode				=	RRCode
		AC_1_v_Region				=	Region
		AC_1_v_BusinessLine			=	BusinessLine
		AC_1_v_Product				=	Product
		AC_1_v_Coveragestartdate	=	Coveragestartdate
		AC_1_v_Coverageenddate		=	Coverageenddate
		AC_1_v_Coveragetype			=	Coveragetype
		AC_1_v_Coverage%			=	Coverage%
		AC_1_v_Status				=	Status
		AC_1_v_Confidential			=	Confidential
		
		Investment_Focus_Details:
		AC_1_v_DominantInvestmentStyle			=	DominantInvestmentStyle
		AC_1_v_InvestmentOrientation			=	InvestmentOrientation
		AC_1_v_TypeofInvestment					=	TypeofInvestment
		AC_1_v_SizeofInvestment					=	SizeofInvestment
		AC_1_v_PreferredInvestmentSector		=	PreferredInvestmentSector
		AC_1_v_PreferredInvestmentSub-Sector	=	PreferredInvestmentSub-Sector
		AC_1_v_PreferredInvestmentLocation		=	PreferredInvestmentLocation
		AC_1_v_PreferredMarketCap				=	PreferredMarketCap
		AC_1_v_PreferredCompanyMetrics			=	PreferredCompanyMetrics
		