Prism_AddTask= A_T_1

DashBoard=//li[@data-module='Dashboard']/a
PrismUpdate_ToastClose=//button[@class='toast-close-button']



A_T_1_id_Task_Heading=(//h5[@title='Tasks'])[1]
A_T_1_id_Task_Add_Btn=//button[@id='task_add']
A_T_1_id_Assgine_Name=//ul[@id='task_assigntosearch']//li//input
A_T_1_id_SelAssgine_Name=//ul[@id='task_assigntosearch']//li//span
A_T_1_id_Assgine_Dropdown_Click=(//ul[@class='Dropdown']//li)[1]
A_T_1_id_DueDate=taskDueDate
A_T_1_id_SelDueDate=//*[@id='taskDueDate']
A_T_1_id_DueTime=//input[@id='taskDueTime']
A_T_1_id_Tasktype=//select[@id='taskType']//option[3]
A_T_1_id_SelectedTasktype=//select[@id='taskType']
A_T_1_id_Task_Status=//select[@id='taskStatus']//option[3]
A_T_1_id_Selected_TaskStatus=//select[@id='taskStatus']
A_T_1_id_Subject=//input[@id='taskSub']
A_T_1_id_Contacts=//ul[@id='contactsTasksearch']//li//input
A_T_1_id_Contacts_Dropdown_Click=(//ul[@class='Dropdown']//li)[1]
A_T_1_id_Description=//textarea[@id='taskComments']
A_T_1_id_Task_Save_Btn=//input[@id='taskSave']

Verification :
A_T_1_id_Task_verifyTable=(//table[@class='table task-table no-margin'])[1]

A_T_1_id_Task_verifyAssgineName=


A_T_1_id_BurgerBtn=(//span[@class='icon c-pointer icon-menu-1 icon-xs'])[1]
A_T_1_id_Task_EditIcon=(//ul//li[@class='summary_edit_task'])[1]
A_T_1_id_Task_DeleteIcon=(//li[text()='Delete'])[1]
A_T_1_id_Taskpage_crossClose=//div[@id='Task']//button[1]/span[1]
A_T_1_id_Confirm_Close=//button[@id='taskCloseConf']

A_T_1_id_TaskExpand_Btn=(//a[@class='fullscreen-link']//i)[3]
A_T_1_id_Task_tableHeader=//div[@class='dataTables_scrollHeadInner']//table[@class='compact task-detail-table table-striped table-bordered theme-table table data-ellipsis custDataTable nowrap dataTable no-footer']//thead//th
A_T_1_id_Task_Name=//div[@class='dataTables_scrollHeadInner']//table[@class='compact task-detail-table table-striped table-bordered theme-table table data-ellipsis custDataTable nowrap dataTable no-footer']//thead//th
A_T_1_id_Task_AccountName=
A_T_1_id_Task_ContactName=




Analyst Table:
    EE_1_1_Eventinfo_analysttable=//*[@data-fixedid='emv2eventinfoanalystdatatable']
	EE_1_1_Eventinfo_analysttable_HeaderCount=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th
	EE_1_1_Eventinfo_analysttable_rowCount=//table[@data-fixedid='emv2eventinfoanalystdatatable']//tbody//tr
	EE_1_1_Eventinfo_analysttable_Name=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th[text()='Name']
	EE_1_1_Eventinfo_analysttable_phone=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th[text()='Phone']
	EE_1_1_Eventinfo_analysttable_Mobil=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th[text()='Mobile']
	EE_1_1_Eventinfo_analysttable_indexposition=//table[@data-fixedid='emv2eventinfoanalystdatatable']//tbody//tr[row]//td[index_posi]
	

TestCases:
Values:TestcasePath	
	A_T_1_v_testCasePath=\\TestCases\\AddTask\\AddtaskValues.xlsx
	A_T_1_v_Row=row id
    A_T_1_v_AssigneName=Assigne Name
    A_T_1_v_DueDate =Due Date
    A_T_1_v_DueTime=ClockTime
    A_T_1_v_Subject=Subject
    A_T_1_v_Contacts=Contacts
    A_T_1_v_Contacts1=Contacts1
    A_T_1_v_Description=Description
    
    
    
    The time entered is incorrect. Please enter the time in HH:MM AM/PM format.
    Please select a Task Status
    Please select a Task Type
    Please enter a Subject
    Please select a contact
    
    
    
    
    
    
