GlobalSearchConfig:
	GS_id_globalSearch			= //*[@id="top-search"]
	GS_id_tickercheck			= TIC
	GS_id_propspectcheck		= PROS
	GS_id_contactcheck			= CON
	GS_id_usercheck				= USR
	GS_id_coveredaccs			= ACREV
	GS_id_eventcheck			= EVNT
	GS_id_superaccountcheck		= SAC
	GS_id_globalsearchlist 		= //*[@class="typeahead-result globalSettingResult"]//ul
	GS_id_empty_search_result	= //*[@class="typeahead-result globalSettingResult"]//ul/li[@class="typeahead-empty"]
	GS_id_filter_check_area		= //div[@class="filter-check-area"]
	GS_id_tearSheet_header 		= //ul[@id='panelHeadTab']//li[contains(@title,'{value}')]
	GS_id_tearSheetClose 		= //*[@id='panelHeadTab']//button[@title='Close']
	GS_id_Partial_Macth_contact = //*[@data-group="Contact"] //child::*[contains(text(),"?")]
	GS_id_Partial_Macth_ticker  = //*[@data-group="Ticker"] //child::*[starts-with(substring-before(text(),'-'),"?")]
	GS_id_Partial_Macth_account = //*[@data-group="Account"] //child::*[contains(text(),"?")]
UserRoleConfig:
	1_EquityHead = equity|new
	2_SalesPerson = sales|new
	3_Analyst = analyst|new
	4_SalesAssistant = sassistant|new
CommonLoadingScreen:
	prism_loading_screen = loading_screen
	
modulewiseControl: 1 -  enable, 0 - disable
	moduleControl = 0