Contact_Verification_WebElements			=	CV_1

	CV_1_id_TopSearchBox					=	top-search
	CV_1_id_AppPage							=	//div[@id="appTsheetContainer"]/following-sibling::div
	CV_1_id_Filter_count_List				=	//div[@id='wrapper']//div[@class='filter-check-area']//div
	CV_1_id_Filter_Selected_Check			=	//div[@id='wrapper']//div[@class='filter-check-area']//div[temp]/input
	CV_1_id_Filter_Deselect					=	//div[@id='wrapper']//div[@class='filter-check-area']//div[temp]/label
	CV_1_id_Contact_FilterCheckBox			=	//div[@id='wrapper']//label[@title='Contact']
	CV_1_id_ContactSearchListPresentornot	=	//div[@id='wrapper']//div[@class='typeahead-result globalSettingResult']//li/a[1]
	CV_1_id_ContactSearchList				=	//div[@id='wrapper']//div[@class='typeahead-result globalSettingResult']//li[@class='typeahead-item']
	CV_1_id_ContactEmailSearchList			=	//div[@id='wrapper']//div[@class='typeahead-result globalSettingResult']//li[@class='typeahead-item'][temp]//span//div[contains(@class,'mail')]
	CV_1_id_RequiredContactMail				=	//div[@id='wrapper']//div[@class='typeahead-result globalSettingResult']//li[@class='typeahead-item'][temp]
	CV_1_id_ContactTearSheetPage			=	//div[@id='search_header_slide']/parent::div
	CV_1_id_InterestListTab					=	//div[@id='appTsheetContainer']//a[text()='Interest List']
	CV_1_id_InterestPage					=	(//div[@id="appTsheetContainer"]//div[contains(@id,'tabs panelcont')])[7]
	CV_1_id_AddButton						=	toggleInterest
	CV_1_id_InterestAddBox					=	//div[@id='page-wrapper']//div[@class='interest-form panel-form panel-grey form-xl']
	CV_1_id_TickerSearch					=	tickerSrchText
	CV_1_id_TickerOrSectorSrchPrnstornot	=	//div[@id='page-wrapper']//div[@class='typeahead-result']//a[1]
	CV_1_id_TickerListDisplayed				=	(//div[@id='page-wrapper']//div[@class='typeahead-result']//a[@data-group='TICKER'])
	CV_1_id_SectorListDisplayed				=	(//div[@id='page-wrapper']//div[@class='typeahead-result']//a[@data-group='SECTOR'])
	CV_1_id_TickerSearchListDisplayed		=	(//div[@id='page-wrapper']//div[@class='typeahead-result']//a[@data-group='TICKER']//span)
	CV_1_id_SectorSearchListDisplayed		=	(//div[@id='page-wrapper']//div[@class='typeahead-result']//a[@data-group='SECTOR']//span)
	CV_1_id_TickerSelect					=	//div[@id='page-wrapper']//div[@class='typeahead-result']//a[@data-group='TICKER']//span[text()="temp"]
	CV_1_id_SectorSelect					=	//div[@id='page-wrapper']//div[@class='typeahead-result']//a[@data-group='SECTOR']//span[text()="temp"]
	CV_1_id_InterestComments				=	interestComments
	CV_1_id_InterestSelect					=	//div[@id='appTsheetContainer']//div[@data-option='interest']//i[@class='icon icon-temp']
	CV_1_id_interestAddButton				=	addInterest
	CV_1_id_TableTickerValue				=	//div[@id='appTsheetContainer']//table[contains(@id,'interestList-table')]//td[temp]
	CV_1_id_TableInterest					=	//div[@id='appTsheetContainer']//table[contains(@id,'interestList-table')]//td[temp]//i
	CV_1_id_TableComments					=	//button[@id='cmnt-acty-account']/parent::td
	CV_1_id_TableDeleteRow					=	//div[@id='deleteRow']/i
	CV_1_id_TableDeleteRowConfirmPage		=	//div[@id='dashboard_popup']//div[@class='modal-content']
	CV_1_id_TableDeleteRowConfirmButton		=	confirmInterestDelete
	CV_1_id_TableCommentsFilter				=	(//div[contains(@id,'interestList-table')]//div[@class="btn-group bootstrap-select show-tick multiselect-filters"])[temp]/button
	CV_1_id_TableCommentsInput				=	(//div[@id='appTsheetContainer']//button[@class='btn dropdown-toggle bs-placeholder btn-default'])[temp]/following-sibling::div//input
	CV_1_id_TableCommentsListSelect			=	(//div[@id='appTsheetContainer']//ul[@class="dropdown-menu inner"]//span[@title="temp"])[1]
	CV_1_id_TableFilterButton				=	(//div[@id='appTsheetContainer']//button[@class='btn dropdown-toggle btn-default'])[1]/following-sibling::div//button[text()='Filter']
	CV_1_id_ContactCloseButton				=	//div[@id='page-wrapper']//button[@title='Close']
	CV_1_id_TickerPosition					=	//div[contains(@id,'interestList-table')]//thead//tr[3]/th[text()='Ticker']
	CV_1_id_InterestPosition				=	//div[contains(@id,'interestList-table')]//thead//tr[3]/th[text()='Interest']
	CV_1_id_CommentPosition					=	//div[contains(@id,'interestList-table')]//thead//tr[3]/th[text()='Comments']
	CV_1_id_AllPosition						=	//div[contains(@id,'interestList-table')]//thead//tr[3]/th
	CV_1_id_CommentsList					=	(//div[@id='appTsheetContainer']//ul[@class="dropdown-menu inner"]/li/a/span)[temp]
	CV_1_id_TableCommentsDisplayed			=	//table[contains(@id,'interestList-table')]//td[1]
	CV_1_id_ToastCloseButton				=	//div[@id='toast-container']//button[@class='toast-close-button']

Contact_Verification_Values:

	CV_1_v_case_from_excel					=	1
	CV_1_v_test_case_path					=	\\TestCases\\ContactVerification\\contactverification.xlsx
	CV_1_v_row_id							=	Row_Id
	CV_1_v_Contact_Name						=	Contact_Name
	CV_1_v_Contact_Email					=	Contact_EmailID
	CV_1_v_Ticker/SectorSuggName			=	Ticker/SectorSugg
	CV_1_v_Ticker/SectorName				=	Ticker/SectorName
	CV_1_v_Comments							=	Comments
	CV_1_v_InterestType						=	InterestType
		