AddContactWebElements=CC_1
	CC_1_id_action_plus_icon   = //*[@id='header_action_button']//button[@id="header_action_button_icon"]
	CC_1_id_add_contact_button =//*[@id="headerAddContactv2"]
	CC_1_id_add_contact_form = //div[@id="contact-crm-modal-content"]//div[@class="contact_crm_model modal-body"]//form[@id="add_update_contact_form"]
	CC_1_id_add_contact_info_tab = //div[@class="tabs-container reportTabsContainer pageTabs contactMgnt fw-100"]//li[@id="contactInfoli"]
	CC_1_id_add_contact_info_page = //div[@id="contactInfo"]
	CC_1_id_add_contact_info_pageclick = //li[@id="contactInfoli"]//a
	CC_1_id_add_contact_bio_tab = //li[@id="contactBioli"]//a 
	CC_1_id_add_investment_profile_tab =//li[@id="investmentProfli"]//a
	CC_1_id_add_research_accesss_tab =//li[@id="researchAccessli"]//a
	 
	Contact Basic Info : 
	CC_1_id_firstname_field = //label[@for="contactInfo_firstName"]
	CC_1_id_add_firstname      =//div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//input[@id="contactInfo_firstName"]
	CC_1_id_firstname_label = //label[@for="contactInfo_firstName"]
	CC_1_id_lastname_field = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//input[@id="contactInfo_lastName"]
	CC_1_id_add_lastname       =//div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//input[@id="contactInfo_lastName"]
	CC_1_id_contactype_field =   //*[@id='contactInfo_contactType'] 
	CC_1_id_contactype_optionselect = //select[@id="contactInfo_contactType"]//option[@value='?']
	CC_1_id_contactype_option = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//ul[@class="panel-form form-lg"]//li[@class="form-fields h-t-sm  mandatry "]//select[@id="contactInfo_contactType"]//option
	CC_1_id_contactype_corporate = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//ul[@class="panel-form form-lg"]//li[@class="form-fields h-t-sm  mandatry "]//select[@id="contactInfo_contactType"]//option[@value="Corporate"]
	CC_1_id_contactype_investor = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//ul[@class="panel-form form-lg"]//li[@class="form-fields h-t-sm  mandatry "]//select[@id="contactInfo_contactType"]//option[@value="Investor"]
	CC_1_id_contacttype        = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_contactType"]
	CC_1_id_contactyp_option   = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_contactType"]//option[@value='
	CC_1_id_accountname_field = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//li[@class="form-fields h-t-sm  c-break mandatry "]//input[@id="contactInfo_accountId"]
	CC_1_id_accountname        =  //input[@id="contactInfo_accountId"]
	CC_1_id_accountname_dropdown =  //*[@data-group="search"]/span[contains(text(),'?')]
	CC_1_id_select_jobfunc =//div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_jobFunc"]
	CC_1_id_select_jobfunc_dropdown_value = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_jobFunc"]/option[text()='?']
	CC_1_id_jobfun_option = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_jobFunc"]//option[@value='
	CC_1_id_jobfunoption = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_jobFunc"]//option[
	CC_1_id_joboption = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//select[@id="contactInfo_jobFunc"]//option[@value]
	CC_1_id_jobtitle = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//input[@id="contactInfo_jobTitle"]
	
	Email Info:
	CC_1_id_primary_email  =//*[@id='contactInfo_contactEmail']
	CC_1_id_email1 = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//input[@id="contactInfo_contactEmail1"]
	CC_1_id_email2 = //div[@id="contact-crm-modal-content"]//div[@id="contactInfo"]//input[@id="contactInfo_contactEmail2"]
	CC_1_id_deskwork_field = //label[@for="contactInfo_phoneNo"]//parent::li
	CC_1_id_desk_select_country = //label[@for="contactInfo_phoneNo"]//parent::li//child::div[@class='selected-flag']
	CC_1_id_desk_input       =//*[@id='contactInfo_phoneNo']
	 CC_1_id_mobile_field = //label[@for="contactInfo_phoneNo1"]//parent::li
	CC_1_id_mobile_select_country = //label[@for="contactInfo_phoneNo1"]//parent::li//child::div[@class='selected-flag']
	CC_1_id_mobile_input       =//*[@id='contactInfo_phoneNo1']
	 CC_1_id_home_field = //label[@for="contactInfo_phoneNo2"]//parent::li
	CC_1_id_home_select_country = //label[@for="contactInfo_phoneNo2"]//parent::li//child::div[@class='selected-flag']
	CC_1_id_home_input       =//*[@id='contactInfo_phoneNo2']
	CC_1_id_extensionfield = //input[@id="contactInfo_phoneExtn"]
	CC_1_save_button=//button[@id="btn_add_contact"]
	CC_1_contact_actions = //div[@class="buttonPanel"]//div[@class="dropdown"]//i[@class="icon icon-list-2 icon-xs dropdown-toggle c-pointer"]
	CC_1_contact_hisryclick = //*[@id="contact_history"]//a
	CC_1_id_loginUsername = //*[@class="m-t-xs  m-r-md usr_name profileName"]
	CC_1_id_contactname = //div[@id="contactHistory"]//div[@class="DM-header modal-subhead bg-primaryLight"]//h2
	CC_1_id_histdate = //div[@id="contactHistory"]//div[@class="DH-container"]//div[@class="tab-content"]//div[@id="AllCont"]//span[@class="DH-date"]
    CC_1_id_histtime = //div[@id="contactHistory"]//div[@class="DH-container"]//div[@class="tab-content"]//div[@id="AllCont"]//span[@class="DH-time"]
    CC_1_id_histusername = //div[@id="contactHistory"]//div[@class="DH-container"]//div[@class="tab-content"]//div[@id="AllCont"]//p[@class="DH_name"]//strong
    CC_1_id_histstatus = //div[@id="contactHistory"]//div[@class="DH-container"]//div[@class="tab-content"]//div[@id="AllCont"]//p[@class="DH_status"]//span
    CC_1_id_histclose = //div[@id="contactHistory"]//button[@class="close"]
    CC_1_tab_close = //div[@class="panel-head"]//ul[@id="panelHeadTab"]//li//button[@class="icon menu-svg icon-xs1 icon-close pull-right thseet-close-icn"]
Address info:
    CC_1_id_address1_field  =//label[@for="contactInfo_ofcAdrs"]//parent::li
    CC_1_id_address1_input  = //*[@id='contactInfo_ofcAdrs']
    CC_1_id_address2_field  =//label[@for="contactInfo_ofcAdrs1"]//parent::li
    CC_1_id_address2_input  =//*[@id='contactInfo_ofcAdrs1']
    CC_1_id_city_field      = //label[@for="contactInfo_ofcCity"]//parent::li
    CC_1_id_city_input      =//*[@id='contactInfo_ofcCity']
    CC_1_id_state_field     =//label[@for="contactInfo_ofcState"]//parent::li
    CC_1_id_state_input     =//*[@id='contactInfo_ofcState']
    CC_1_id_country_field   =//label[@for="contactInfo_ofcCtry"]//parent::li
    CC_1_id_country_input   =//*[@id='contactInfo_ofcCtry']
    CC_1_id_zip_field       =//label[@for="contactInfo_ofcZip"]//parent::li
    CC_1_id_zip_input       =//*[@id='contactInfo_ofcZip']
Work Assistants info:
    CC_1_id_assistant_name_field       =//label[@for="contactInfo_asstName"]//parent::li
    CC_1_id_assistant_name_input       =//*[@id='contactInfo_asstName']
    CC_1_id_assistant_email_field      =//label[@for="contactInfo_asstEmail"]//parent::li
    CC_1_id_assistant_email_input      =//*[@id='contactInfo_asstEmail']
    CC_1_id_assistant_phone_field      =//label[@for="contactInfo_asstPhone"]//parent::li
    CC_1_id_assistant_phone_input      =//*[@id='contactInfo_asstPhone']
    CC_1_id_assistant_phone_select_country = //label[@for="contactInfo_asstPhone"]//parent::li//child::div[@class='selected-flag']
    
    //get dial code  //*[@class='selected-dial-code']
    //select flag  //*[@class='selected-flag']
    //dropdown  //*[@class='country-list']
General Preferences info:
    CC_1_id_preferred_name_field      =//label[@for="contactInfo_prefName"]//parent::li
    CC_1_id_preferred_name_input      =//*[@id='contactInfo_prefName']
     
    CC_1_id_preferred_comm_field      =//label[@for="contactInfo_prefComm"]//parent::li
    CC_1_id_preferred_comm_input      =//*[@id='contactInfo_prefComm']
    CC_1_id_preferred_comm_input_dropdown = //*[@id='contactInfo_prefComm']//option[@value='?']
    CC_1_id_emailOpt                   =//*[@id='contactInfo_emailOptOut']//parent::*
    CC_1_id_MiFID                   =//*[@id='contactInfo_doNotCall']//parent::*
    CC_1_id_event                   =//*[@id='contactInfo_eventsOptOut']//parent::*
     
    
General notes:
     CC_1_id_contact_note_field      =//label[@for="contactInfo_contactNotes"]//parent::li
     CC_1_id_contact_note_input      =//*[@id='contactInfo_contactNotes'] 
       




close contact creation page:
    CC_1_id_close_page= //*[@id='close_add_update_contact']
    CC_1_id_close_page_yes= //*[@id='contCloseConf']
    CC_1_id_check_save_contact =//ul[@id="panelHeadTab"]/li
    
close tab:
	CC_1_id_close_tab = //*[@id='panelHeadTab']//child::button     
Working At Info :
	CC_1_id_officeregion = //*[@id="contactInfo_contactRegion"] 
	
	
Contact bio details:
  
CC_1_id_education =     //*[@id="contactBio_education"] 
CC_1_id_emp_history =     //*[@id="contactBio_empHistory"] 	
CC_1_id_firms =     //*[@id="contactBio_firmManaged"] 	
CC_1_id_tr_id =     //*[@id="contactBio_trID"] 
CC_1_id_ipreo_id =     //*[@id="contactBio_tp4_contact_id"] 

investment profile details:
 CC_1_id_invest_style   = //*[@id="investmentProf_investStyle_chosen"]//child::input 	
 CC_1_id_invest_country   = //*[@id="investmentProf_countrySpl_chosen"]//child::input   
 CC_1_id_invest_region   = //*[@id="investmentProf_regionSpl_chosen"]//child::input
 CC_1_id_invest_macro   = //*[@id="investmentProf_macSectorSpl_chosen"]//child::input 
 CC_1_id_invest_mid   = //*[@id="investmentProf_subSectorSpl_chosen"]//child::input 
 CC_1_id_invest_industry  = //*[@id="investmentProf_industrySpl_chosen"]//child::input 
 CC_1_id_invest_market_cap   = //*[@id="investmentProf_marketCapSpl_chosen"]//child::input   
  
Research Access details:
  CC_1_id_research_Email_Primary_checkbox = researchAccess_researchEmailPrimary  	
  CC_1_id_research_Email_input    =	//*[@id="researchAccess_researchMail"] 
  CC_1_id_research_service_Provider_dropdown   =	//*[@id="researchAccess_serviceProvider?"] 
  /need fix id
  CC_1_id_research_service_add_button =//*[@id='researchAccess_serviceProvider']//parent::li//parent::ul//child::button[contains(@class,'add')]
  CC_1_id_research_service_add_button2 =//div[@id='researchAccess']//child::div[@id="additionalrow?"]//li[last()]//button[contains(@class,'add')]
  CC_1_id_research_service_close_button =//*[@id='researchAccess_serviceProvider']//parent::li//parent::ul//child::button[contains(@class,'close')]
  CC_1_id_end_date   = researchAccess_proEndDate?
  CC_1_id_user_name_insert = researchAccess_resUserName_BlueMatrix_generate_username
  CC_1_id_generate_password = researchAccess_resPass_BlueMatrix_generate_pass
  
  
 get Account details:
     CC_1_id_search = top-search 
     CC_1_id_ticker_checkbox = //*[@id="TIC"]
     CC_1_id_prospect_checkbox = //*[@id="PROS"]
     CC_1_id_super_account_checkbox = //*[@id="SAC"]
     CC_1_id_account_checkbox = //*[@id="ACREV"]
     CC_1_id_search_dropdown =  //*/span[?]
     CC_1_id_account_edit   =  //div[@class='dropdown']//i[@data-toggle="dropdown"] 
     CC_1_id_account_edit_dropdown =   // li[@id="editAccountCrm"] | // li[@id="editTickerAccountCrm"] 
     CC_1_id_account__ticker_edit_dropdown =// *[@id="editTickerAccountCrm"]  
     CC_1_id_account_type   = // *[@name="ac"]  
     CC_1_id_account_type_Corporate =  // *[@id="Corporate"] 
     CC_1_id_account_office_detail_tab = //*[@data-tabid='?_officeDetails']
     CC_1_id_account_office_detail_table =   //*[@id='table-?_officeDetails_officeDetailsTable']//child::tbody/tr 
     CC_1_id_account_page_close = // *[@id="add-account"]//child::button
     CC_1_id_account_page_close_ok=close_ok
     
contact header details:

    CC_1_id_acc_contactname          = //span[@id='con_nme']
    CC_1_id_acc_accountLink          =  //span[@id='con_account']
    CC_1_id_acc_address              = //span[@id='con_address']
    CC_1_id_acc_desk_no              = //span[@id='con_phone_no']
    CC_1_id_acc_primary_email        =  //span[@id='con_mail0']
    CC_1_id_acc_secondary_email      = //span[@id='con_mail1']
    CC_1_id_acc_personal_email       = //span[@id='con_mail2']
    CC_1_id_acc_status               = //span[@id='active_status']
    CC_1_id_assistant_name           =  //*[@data-fixedid="tccontacttearsheetassistantname"]
    CC_1_id_assistant_mobile         =  //*[@data-fixedid="tccontacttearsheetassistantmobile"]
    CC_1_id_assistant_email          =  //*[@data-fixedid="tccontacttearsheetassistantemail"]
Contact bio details:  
    CC_1_id_more                     =  //*[@data-fixedid="tccontacttearsheetbiomorebutton"]
    CC_1_id_c_education              =  //div[@class="bio-eductn"]//span[contains(text(),"Education:")]//parent::div
    CC_1_id_c_education_his          =  //div[@class="bio-eductn"]//span[contains(text(),"Employment History:")]//parent::div
    CC_1_id_c_firms                  =  //div[@class="bio-eductn"]//span[contains(text(),"Firms Formerly Managed:")]//parent::div
    CC_1_id_c_preferName             =  //div[@class="bio-eductn"]//span[contains(text(),"Preferred Name:")]//parent::div
    CC_1_id_c_style                  =  //*[@data-fixedid="tccontacttearsheetbiostyle"] 
	CC_1_id_c_Orientation            =  //*[@data-fixedid="tccontacttearsheetbioorientation"] 
	CC_1_id_c_market_cap             =  //*[@data-fixedid="tccontacttearsheetbiomarketcap"] 
	CC_1_id_c_micro_ind              =  //*[@data-fixedid="tccontacttearsheetbiomicroindustry"] 
	CC_1_id_c_mid_ind                = //*[@data-fixedid="tccontacttearsheetbiomidindustry"] 
	CC_1_id_c_focus_reg              =  //*[@data-fixedid="tccontacttearsheetbiofocusregion"] 
	CC_1_id_c_focus_coun             =  //*[@data-fixedid="tccontacttearsheetbiofocuscountry"] 
	CC_1_id_c_macro_ind             =  //*[@data-fixedid="tccontacttearsheetbiomacroindustry"] 
	CC_1_id_c_contact_notes          =  //*[@data-fixedid="tccontacttearsheetbiocontactnotes"]   
	CC_1_id_c_close                  =  //*[@data-fixedid="tccontacttearsheetbioclosebutton"]    
    
    
    
MandatoryFiledValidationRowConfig:
	CC_1_v_testCasePath    	= \\TestCases\\contactcreate\\CC_1_contact_Create.xlsx
	CC_1_v_rowid            = addrowid
	CC_1_v_firstname        = firstname
	CC_1_v_lastname         = lastname
	CC_1_v_contact_type_auto =  contact type auto
	CC_1_v_contacttype      = contacttype
	CC_1_v_account      = account
	CC_1_v_jobfunction      = job function
	CC_1_v_primaryemail     = primary email
	CC_1_v_secondarymail = secondary mail
	CC_1_v_personalmail = personal mail
	CC_1_v_jobtitle = Job title
	CC_1_v_desk = desk
	CC_1_v_mobile = mobile
	CC_1_v_extension = extension
	CC_1_v_home = home
	CC_1_v_address1 = address1
	CC_1_v_address2 = address2
	CC_1_v_city = city
	CC_1_v_state = state
	CC_1_v_country =country
	CC_1_v_zip = zip
	CC_1_v_assistant_name= assistant name
	CC_1_v_assistant_email = assistant email
	CC_1_v_assistant_phone = assistant phone
	CC_1_v_preferred_name = preferred name
	CC_1_v_preferred_comm = preferred comm
	CC_1_v_emailopt =emailopt
	CC_1_v_MiFID  = MiFID 
	CC_1_v_event = event
	CC_1_v_contact_note =contact note 
	CC_1_v_Employment_History =Employment History
	CC_1_v_education =education
	CC_1_v_firms =firms
	CC_1_v_trid =trid
	CC_1_v_ipreoid =ipreoid
	CC_1_v_Investment_Style =Investment Style
	CC_1_v_Investment_country = Investment country
	CC_1_v_Investment_region = Investment region
	CC_1_v_Investment_macro =Investment macro
	CC_1_v_Investment_mid =Investment mid
	CC_1_v_Investment_Industry =Investment Industry
	CC_1_v_Investment_marketCap = Investment marketCap
	CC_1_v_Research_Email_checkbox = Research Email checkbox
	CC_1_v_Research_Email_ID = Research Email ID
	
	
	
	
Account Edit in office detail tab in table heading
    CC_1_v_acc_office= office
    CC_1_v_acc_address =streetAddress1
	CC_1_v_acc_city= city
	CC_1_v_acc_state= stateCountry
	CC_1_v_acc_country= country
	CC_1_v_acc_zip= zipPostalCode
	CC_1_v_acc_alternatePhone= alternatePhoneNo 
	CC_1_v_acc_fax= faxNo  
	CC_1_v_acc_region= mifIdRegion  
	       
	
MandatoryFiledToastTextConfig:
	CC_1_v_toast_warning = 	Please fill First Name
	CC_1_v_last_warning = Please fill Last Name
	CC_1_v_contact_type_warning = Please fill Contact Type
	CC_1_v_account_name = Please fill Account Name
	CC_1_v_job_function_warning = Please fill Job Function
	CC_1_v_primary_email = Please fill Email
	CC_1_v_mail_valid = Please enter a valid email address
	CC_1_v_desk_valid=Please enter a valid phone number
	CC_1_v_user_name =Please Enter User name
	