ContactMove=CM_1
	 	CM_1_v_testCasePath = \\TestCases\\contactmove\\CM_1_contact_move.xlsx
	 	
Global search details:
 
 CM_1_id_search = top-search 
 CM_1_id_account_checkbox  = //*[@id="ACREV"]
 CM_1_id_contact_checkbox  = //*[@id="CON"]
 CM_1_id_search_dropdown   = //*[@data-group="Account"] /span[text()='?']
 CM_1_id_search_contact_dropdown  = //*[@data-group="Contact"]//child::div[text()="?"]
 Account tear sheet details :
 CM_1_id_account_edit     =  //div[@class='dropdown']//i[@data-toggle="dropdown"] 
 CM_1_id_contact_tab      = //li[@data-index=3]/a[contains(text(),'Contacts')]  
 CM_1_id_account_id       = //ul[@id='panelHeadTab']/li[@title="Account - ?"]   
 CM_1_id_contact_table_id = //table[@id='AC_?_tsheet_page_AC_1173_1286_contacts-table']      
 CM_1_id_contact_edit     = //table[@id='AC_?_tsheet_page_AC_1173_1286_contacts-table']/tbody/tr[1]/td[2] 
 CM_1_id_contact_id       =   //table[@id='AC_?_tsheet_page_AC_1173_1286_contacts-table']/tbody/tr[1]/td[1] 
 
 
 contact tear sheet:
 
 
 CM_1_id_header_tab_id            = //*[@id="panelHeadTab"]/li/a
 CM_1_id_h_account_name           =  // *[@id="con_account"] 
 CM_1_id_h_contact_name          =  // *[@id="con_nme"] 
 CM_1_id_contact_edit_dropdown    =  // *[@id="move_contact_crm"] 
 CM_1_id_contact_edit_button      =  //div[@id="search_CT_?"]//child::div[@class='dropdown']/i[@data-toggle="dropdown"]
 CM_1_id_contact_header_tab       =  //a[@data-id="?"]   
 CM_1_id_contact_name             =  //input[@id="con_Name"]
 CC_1_id_con_primary_email 		  =  //span[@id='con_mail0']
 CM_1_id_from_account_name        =  //input[@id="from_account_move"]
 CM_1_id_to_account_name          =  //input[@id="to_account_move"]
 CM_1_id_to_account_name_dropdown =  //a[@data-group="search"]/span[contains(text(),"?")]
 CM_1_id_move_button              =  //*[@id="btn_move_contact"]
 CM_1_id_move_page_close          =  //*[@id="close_deactive_contact"]    
 CM_1_id_history                  =  (//div[@id="AllCont"]//p[contains(text(),"Changed the Account from ")])[1]/span
 CM_1_id_more                     =  //*[@data-fixedid="tccontacttearsheetbiomorebutton"] 
 CM_1_id_c_education              =  //div[@class="bio-eductn"]//span[contains(text(),"Education:")]//parent::div
 CM_1_id_c_education_his          =  //div[@class="bio-eductn"]//span[contains(text(),"Employment History:")]//parent::div
 CM_1_id_c_firms                  =  //div[@class="bio-eductn"]//span[contains(text(),"Firms Formerly Managed:")]//parent::div
 CM_1_id_c_preferName             =  //div[@class="bio-eductn"]//span[contains(text(),"Preferred Name:")]//parent::div
 CM_1_id_c_style                  =  //*[@data-fixedid="tccontacttearsheetbiostyle"] 
 CM_1_id_c_Orientation            =  //*[@data-fixedid="tccontacttearsheetbioorientation"] 
 CM_1_id_c_market_cap             =  //*[@data-fixedid="tccontacttearsheetbiomarketcap"] 
 CM_1_id_c_micro_ind              =  //*[@data-fixedid="tccontacttearsheetbiomicroindustry"] 
 CM_1_id_c_focus_reg              =  //*[@data-fixedid="tccontacttearsheetbiomidindustry"] 
 CM_1_id_c_focus_coun             =  //*[@data-fixedid="tccontacttearsheetbiofocuscountry"] 
 CM_1_id_c_contact_notes          = //*[@data-fixedid="tccontacttearsheetbiocontactnotes"] 
 CM_1_id_c_close                  = //*[@data-fixedid="tccontacttearsheetbioclosebutton"] 
 contact edit details:
 CM_1_id_firstName       = //*[@id="contactInfo_firstName"]
 CM_1_id_lastName        = //*[@id="contactInfo_lastName"]
 CM_1_id_accountName     = //*[@id="contactInfo_accountId"]
 CM_1_id_primaryEmail    = //*[@id="contactInfo_contactEmail"]
 CM_1_id_jobFunction     = //*[@id="contactInfo_jobFunc"]
 CM_1_id_jobFunction_drop_down     = //*[@id="contactInfo_jobFunc"]/option[2]
 CM_1_id_contact_update  = //*[@id="btn_update_contact"] 
 
 contact history:
 
 CM_1_id_contact_edit_button  = //div[@id="search_CT_?"]//child::div[@class='dropdown']/i[@data-toggle="dropdown"]
 CM_1_id_contact_edit_history_dropdown =  // *[@id="contact_history"] 
 CM_1_id_history      = (//div[@id="AllCont"]//p[contains(text(),"Changed the Account from ")])[1]/span
 CM_1_id_all_tab      =  //a[@href ="#AllCont"]
 CM_1_id_close        =  //div[@id="contactHistory"]//child::button[text()="×"]
 
 close tab:
	CC_1_id_close_tab = //*[@id='panelHeadTab']//child::button   
 
alert toast message:
    CM_1_v_same_account =    Contact already exists in this account 
Excel Header Details:
    CM_1_v_from_account = From Account
    CM_1_v_rowid = id 
    CM_1_v_to_account =To Account 
    CM_1_v_contact_mail = contact mail	 	