Module_id = EC1
EC_1_v_testCasePath = \\TestCases\\employmentchange\\EC_1_employment_change.xlsx

global search :

EC_1_id_search = top-search 
EC_1_id_search_contact_dropdown  = //*[@data-group="Contact"]//child::div[text()="?"]
EC_1_id_contact_checkbox         = //*[@id="CON"]

EC_1_id_header_tab_id            = //*[@id="panelHeadTab"]/li/a
EC_1_id_h_account_name           =  // *[@id="con_account"] 
EC_1_id_h_contact_name           =  // *[@id="con_nme"] 
EC_1_id_contact_header_tab       =  //a[@data-id="?"]    
EC_1_id_con_primary_email 		 =  //span[@id='con_mail0']
EC_1_id_contact_edit_button      = //div[@id="search_CT_?"]//child::div[@class='dropdown']/i[@data-toggle="dropdown"]
EC_1_id_more                     =  //*[@data-fixedid="tccontacttearsheetbiomorebutton"] 
EC_1_id_contact_edit_dropdown    =  // *[@id="emp_change_crm"] 

Contact bio:
 EC_1_id_c_education              =  //div[@class="bio-eductn"]//span[contains(text(),"Education:")]//parent::div
 EC_1_id_c_education_his          =  //div[@class="bio-eductn"]//span[contains(text(),"Employment History:")]//parent::div
 EC_1_id_c_firms                  =  //div[@class="bio-eductn"]//span[contains(text(),"Firms Formerly Managed:")]//parent::div
 EC_1_id_c_close                  = //*[@data-fixedid="tccontacttearsheetbioclosebutton"] 


my list:
EC_1_id_mylist_table              =   //*[@data-fixedid="tccontacttearsheetlisttable"] 
EC_1_id_mylist_table_data         =  //*[@data-fixedid="tccontacttearsheetlisttable"]/tbody/tr/td[1]
research subscriptions: 

EC_1_id_research_tab                             = //*[@data-pageobjrefid="CT_156"]
EC_1_id_senior_analyst_subscriptions_table_th    =(//*[contains(text(),"Senior Analyst Subscriptions")]//parent::div//following-sibling::div//child::table/thead)[1]/tr/th
EC_1_id_senior_analyst_subscriptions_table_body  =(//*[contains(text(),"Senior Analyst Subscriptions")]//parent::div//following-sibling::div//child::table/tbody)[1]/tr/td
EC_1_id_cover_ticker_table_heading     =//*[contains(text(),"Covered Ticker Subscriptions")]
EC_1_id_cover_ticker_table_th     = (//*[contains(text(),"Covered Ticker Subscriptions")]//parent::div//following-sibling::div//child::table/thead)[1]/tr/th
EC_1_id_cover_ticker_table_body   = (//*[contains(text(),"Covered Ticker Subscriptions")]//parent::div//following-sibling::div//child::table/tbody)[1]/tr
//
EC_1_id_sector_subscriptions_table_th = (//*[contains(text(),"Sector Subscriptions")]//parent::div//following-sibling::div//child::table/thead)[1]/tr/th
EC_1_id_sector_subscriptions_table_tbody = (//*[contains(text(),"Sector Subscriptions")]//parent::div//following-sibling::div//child::table/tbody)[1]/tr

EC_1_id_product_subscriptions_table_th = (//*[contains(text(),"Product Subscription")]//parent::div//following-sibling::div//child::table/thead)[2]/tr/th
EC_1_id_product_subscriptions_table_body =  (//*[contains(text(),"Product Subscription")]//parent::div//following-sibling::div//child::table/tbody)[2]/tr
 
Interest LIst:
EC_1_id_interest_tab             = //*[@data-pageobjrefid="CT_62" ]
EC_1_id_interest_table_head      = //div[contains(@id,"interestList")]//child::table/thead/tr[3]/th[@tabindex]
EC_1_id_interest_table           = //*[@data-fixedid="tccontacttearsheetinterestlisttable"]
EC_1_id_interest_table_body      = //*[@data-fixedid="tccontacttearsheetinterestlisttable" ]/tbody/tr 
EC_1_id_interest_table_page_count      =//div[contains(@id,"interestList")]//ul[contains(@class,"pagination") ]/li/a[@data-dt-idx]
EC_1_id_interest_next_button     =//li[@class="paginate_button next"]/a

employment change page:

EC_1_id_to_account                 = //*[@id="account_change"] 
EC_1_id_to_account_dropdown        = //*[@data-group="search"] //span[?] 
EC_1_id_contact_bio_checkbox       = //*[@id="contactbio"] 
EC_1_id_subscription_checkbox      = //*[@id="subscription"] 
EC_1_id_interestList_checkbox      = //*[@id="interestList"] 
EC_1_id_distributionList_checkbox  = //*[@id="distributionList"] 
EC_1_id_next_button                = //*[@id="btn_deactivate_change_contact"]
EC_1_id_employment_page_close      = //*[@id="close_deactive_contact"] 

Add contact page :
EC_1_id_to_add_contact_page_close  = //*[@id="close_add_update_contact"] 
EC_1_id_account_name               = //*[@id="contactInfo_accountId"] 
EC_1_id_jobFunction     		   = //*[@id="contactInfo_jobFunc"]
EC_1_id_jobFunction_drop_down      = //*[@id="contactInfo_jobFunc"]/option[2]
EC_1_id_primary_email      		   = //*[@id="contactInfo_contactEmail"] 
EC_1_id_save_contact               = //*[@id="btn_add_contact"]

account tear sheet :
EC_1_id_contact_tab           = //li[@data-pageobjrefid="AC_157"]/a | //li[@data-pageobjrefid="TC_1173"]
EC_1_id_contact_search        =//*[contains(@id,"AC_117") or contains(@id,"TC_117") ]//input[@type="search"] 
EC_1_id_contact_table_data    =//table[@data-fixedid="tcaccounttearsheetcontacttable"]/tbody//child::*[#email]
Alert value : 
 EC_1_v_same_account        = Move to account should be different from the existing account
 EC_1_v_same_primary_email  = Contact email already exists
excel value:
 EC_1_v_contact_mail 			= contact mail
 EC_1_v_from_account 			= From Account
 CM_1_v_to_account   			=To Account 
 EC_1_v_rowid        			= id 
 EC_1_v_cont_bio_checkbox      	= contact bio checkbox
 EC_1_v_subscription_checkbox  	= subscription checkbox
 EC_1_v_intrest_checkbox       	= Interest checkbox
 EC_1_v_Distribution_checkbox  	= Distribution List checkbox 
 EC_1_v_primary_email 			= primary email
 EC_1_v_contact_email           =contact mail
 EC_1_v_inactive_contact        =Email Opt Out
 EC_1_v_my_list_empty           = This contact is not in your lists
 
 