Prism_Existingevent= EE_1_1

prism_Existingevents_Web_Elements:
EE_1_1_id_ListBtn=//button[@data-fixedid='tcemv2eventmangerlistviewbutton']
EE_1_1_id_Search_field=//input[@data-fixedid='tcemv2eventmangerlistviewsearch']
EE_1_1_table_count =//table[@data-fixedid='tcemv2eventmangerlistviewtable']//tbody//tr
EE_1_1_table_rowvalue = //table[@data-fixedid='tcemv2eventmangerlistviewtable']//tbody//tr[list_temp1]//td[1]
EE_1_1_table_Eventtyperow=//table[@data-fixedid='tcemv2eventmangerlistviewtable']//tbody//tr[Event]//td[2]
EE_1_1_table_StartDate=//table[@data-fixedid='tcemv2eventmangerlistviewtable']//tbody//tr[start]//td[3]
EE_1_1_table_EndDate=//table[@data-fixedid='tcemv2eventmangerlistviewtable']//tbody//tr[End]//td[4]
EE_1_1_Month_click=//button[@data-fixedid='tcemv2eventmangermonthviewbutton']

Event Info:
EE_1_1_id_EventInfo_click=//i[@data-fixedid='emv2eventinfoeditevent']
EE_1_1_EventInfo_Selecttype=//*[@data-fixedid='emv2eventinfoselecteventtype']
EE_1_1_id_EventInfo_EventTitle=//*[@data-fixedid='emv2texteventname']
EE_1_1_id_EventInfo_Startdate=//*[@data-fixedid='emv2eventinfostartdate']
EE_1_1_id_EventInfo_Enddate=//*[@data-fixedid='emv2eventinfoenddate']
EE_1_1_id_EventInfo_close_Btn=//button[@data-fixedid='emv2eventinfoclosebutton']

Analyst Table:
    EE_1_1_Eventinfo_analysttable=//*[@data-fixedid='emv2eventinfoanalystdatatable']
	EE_1_1_Eventinfo_analysttable_HeaderCount=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th
	EE_1_1_Eventinfo_analysttable_rowCount=//table[@data-fixedid='emv2eventinfoanalystdatatable']//tbody//tr
	EE_1_1_Eventinfo_analysttable_Name=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th[text()='Name']
	EE_1_1_Eventinfo_analysttable_phone=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th[text()='Phone']
	EE_1_1_Eventinfo_analysttable_Mobil=//table[@data-fixedid='emv2eventinfoanalystdatatable']//th[text()='Mobile']
	EE_1_1_Eventinfo_analysttable_indexposition=//table[@data-fixedid='emv2eventinfoanalystdatatable']//tbody//tr[row]//td[index_posi]
	
Company Table:	
	EE_1_1_Eventinfo_companytable=//table[@data-fixedid='emv2eventinfocompanydatatable']
Co_ordinator Table:
	EE_1_1_Eventinfo_co_ordinatorttable=//table[@data-fixedid='emv2eventinfocoordinatordatatable']


Add Location:
EE_1_1_id_Location_editIcon=//li[1]//i[@data-fixedid='emv2eventaddlocationedit']
EE_1_1_id_AddedLocation_SelectField=//*[@data-fixedid='tcemv2eventinfoaddlocationpopupcity']
EE_1_1_id_AddedLocation_SelectField1=(//*[@data-fixedid='tcemv2eventinfoaddlocationpopupcity'])[temp]
EE_1_1_id_Location_Host=//*[@data-fixedid='emv2selecteventinfoaddlocationnewhost']
EE_1_1_id_SelectField_Location_Host=(//*[@data-fixedid='tcemv2eventinfoaddlocationpopuphost'])[loc_host]
EE_1_1_id_AddedLocation_CloseBtn=//*[@data-fixedid='tcemv2eventinfoaddlocationpopupclosebutton']

Tearsheet:
	EE_1_1_analystheader=//div[@class='analyst-info panel panel-default']
	EE_1_1_analystname1=//div[contains(@class,'analyst-name m-b-xs')]
	EE_1_1_analystphno1=//div[contains(@class,'analyst-desk')]//span
	EE_1_1_analystMobno1=//div[contains(@class,'analyst-mobile')]//span
	EE_1_1_companyheader=//div[@class='info-content company-Prof panel panel-default']
	EE_1_1_companydetails=//div[@class='c-teal']//following-sibling::div
	EE_1_1_marketcap=//div[@class='c-teal'][contains(text(),'Market Cap')]//following-sibling::div
	EE_1_1_rating=//div[@class='c-teal'][contains(text(),'Rating')]//following-sibling::div
	EE_1_1_pricetarget=//div[@class='c-teal'][contains(text(),'Price Target')]//following-sibling::div
	EE_1_1_Ticker=
	EE_1_1_industry=//div[@class='c-teal'][contains(text(),'Industry')]//following-sibling::div
	EE_1_1_companyname=//span[@class='company-name']

Header
EE_1_1_id_Header_EventTitle=//*[@data-fixedid='emv2eventinfoheadereventname']

Tearsheet:Co-ordinator_Header 
EE_1_1_id_Co_ordinator_name=//div[@class='coordinaters-nme-num']//span[@class='co-ordinator-nme']
EE_1_1_id_Co_ordinator_Phone=//div[@class='coordinaters-nme-num']//span[@class='p-l-xs p-r-xs']
EE_1_1_id_Co_ordinator_Mobile=//div[@class='coordinaters-nme-num']//span[4]


Tearsheet Add Location:
EE_1_1_id_Location_Title=//div[@class='title']
EE_1_1_id_Location_Title1=(*//div[@class='title'])[name]
EE_1_1_id_Tearsheet_Location_Host=(//*[@data-fixedid='tcemv2eeventaddlocationhostname'])[Loc_name]



Tearsheet Add Meeting:
EE_1_1_id_S_Meeting_Label=//label[text()='Scheduled list of Meetings:']
EE_1_1_id_S_Meeting_PencilIcon=(//*[@data-fixedid='emv2eventmeetingslotsummaryshow'])
EE_1_1_id_S_Meeting_PencilIcon1=(//*[@data-fixedid='emv2eventmeetingslotsummaryshow'])[pencil]
EE_1_1_id_S_Meeting_Starttime=(//*[@data-fixedid='tcemv2eventmeetingslotstarttime'])[stime]
EE_1_1_id_S_Meeting_EndTime=(//*[@data-fixedid='tcemv2eventmeetingslotendtime'])[Etime]
EE_1_1_id_S_Meeting_MeetingType=(//*[@data-fixedid='tcemv2eventmeetingslotmeetingtype'])[Type]
EE_1_1_id_S_Meeting_Meeting_SubType=(//*[@data-fixedid='tcemv2eventmeetingslotmeetingsubtype'])[Subtype]
EE_1_1_id_S_Meeting_Tags=(//*[@data-fixedid='tcemv2eventmeetingslottags'])[1]
EE_1_1_id_S_Meeting_InternalAttendee=(//*[@data-fixedid='tcemv2eventmeetingslotintattendeelist'])[1]

EE_1_1_id_Incom_Meet_openrequest_UserName=(//*[@data-fixedid='tcemv2eventmeetingslotsectionusername'])[1]
EE_1_1_id_openrequest_AccountName=(//*[@data-fixedid='tcemv2eventmeetingslotsectionacname'])[1]

OpenRequest Tab:
EE_1_1_id_openrequest_Tab_Click=//span[contains(@id,'btnEventRequest')]
EE_1_1_id_openrequest_Close_Btn=//button[@data-fixedid='tcemv2eventrequestclosebutton']


Add Travel:
EE_1_1_id_AddTravel_Tab_Click=//span[contains(@id,'spnEventMeetingSlotCompanyTravel')]
EE_1_1_id_TravelerName_Serchbox=//ul[contains(@id,'selEventTravelTravelerNamesearch')]//li[@class='TokenSearch']//input
EE_1_1_id_TravelerName_Text=//ul[@class="Dropdown"]/li
EE_1_1_id_AddTravel_Close_Btn=(//div[contains(@id,'addtravel-pop')]//button[@class='close'])[1]


Add Hotel:
EE_1_1_id_AddHotel_Tab_Click=//span[contains(@id,'spnEventMeetingSlotCompanyHotel')]
EE_1_1_id_GuestName_SerchBox=//ul[contains(@id,'selEventHotelGuestNamesearch')]//li[@class='TokenSearch']//input
EE_1_1_id_Hotel_GuesName_Text=//ul[@class='Dropdown']//li
EE_1_1_id_AddHotel_Close_Btn=(//div[contains(@id,'addhotel-pop')]//button)[6]


EE_1_1_id_investors_UserNAme=(//*[@data-fixedid='tcemv2eventmeetingslotextattendeeusername'])[1]
EE_1_1_id_investors_AccountName=(//*[@data-fixedid='tcemv2eventmeetingslotextattendeeaccountname'])[1]


Schedule Meeting Slider:
EE_1_1_id_Schedule_Slider_TimeField=(//*[@data-fixedid='tcemv2eventscheduledmeetingslottime'])[1]
EE_1_1_id_Schedule_Slider_Location=(//span[@class='txt-ellipsis']//div)[1]
EE_1_1_id_Schedule_Slider_Typeandsubtype=(//*[@data-fixedid='tcemv2eventscheduledmeetingslottype'])[1]

EE_1_1_id_Schedule_Slider_Tags=(//*[@data-fixedid='tcemv2eventscheduledmeetingslotticker']//h4)[2]





Values:TestcasePath	
	EE_1_1_v_testCasePath =\\TestCases\\Event\\ExistingEventNames.xlsx
	EE_1_1_v_Row=row id
    EE_1_1_v_listsearch_input=Event Names