Login_Submit = LP_1
	Login_in_Web_Elements:
		LP_1_id_useremail    = //input[@id='email']
		LP_1_id_userpassword = //input[@id='paswd']
		LP_1_id_loginButton  = //*[@id='login_tb1']//button[@type='button']
		LP_1_id_errorlabel   = //*[@id='content']
		LP_1_id_Loadedelement= //*[@id='prism_feedback']
		LP_1_id_profileButton= //li[@title="Profile Settings"]//span//label
		LP_1_id_LogoutButton = //li[@title="Profile Settings"]//ul//li//a//span[text()="Logout"]
	Values:
		LP_1_v_case_from_excel = 1
		LP_1_v_testCasePath    = \\TestCases\\login\\LP_1.xlsx
		LP_1_v_useremail       = username
		LP_1_v_userpassword    = password
		LP_1_v_rowid           = rowid
	Default_User:
		LP_1_v_default_Login_user= equity
		LP_1_v_default_Pass      = new