Prism_AccountTearsheetMclagan= ACC_MC_1

D_Dashboard=//li[@data-module='Dashboard']
DashBoard
ACC_MC_1_DashB_Top=//a[@data-tabid='tab-top-clnt']
ACC_MC_1_DashB_SalesHeader=//th[text()='Sales Coverage']
ACC_MC_1_DashB_Search=//div[@id='dataTable_topten_client_collapsed_filter']//input[@placeholder='Search...']
ACC_MC_1_DashB_Icon=//span[@id='page_panel_icon']

ACC_MC_1_AccountTearsheet_CloseBtn=//button[@title='Close']
AC_C_1_PrismUpdatetoast_Close=//button[@class='toast-close-button']

ACC_MC_1_DashB_Top_rowcount=//table[@id='dataTable_topten_client_collapsed']//tbody//tr
ACC_MC_1_DashB_Top_Headercount=//div[@class='dataTables_scrollHeadInner']//table[@data-fixedid='tctopclientsbycommtabledata']//thead//th
ACC_MC_1_DashB_Top_Header_AccountName=//div[@class='dataTables_scrollHeadInner']//table[@data-fixedid='tctopclientsbycommtabledata']//thead//th[@data-fixedid='accName']
ACC_MC_1_DashB_Top_Header_index_position=//table[@id='dataTable_topten_client_collapsed']//tbody//tr[row]//td[index]

Quicklook_MclaganTable:
ACC_MC_1_Quick_MclaganTable=//table[@class='table acc_mclagan theme-table table-striped table-bordered']
ACC_MC_1_Quick_MclaganTable_ExpandBTn=//a[@data-clickid='search_AC_page_5_report_27']//i[1]

Mclagan_Tab_Table:
ACC_MC_1_Mclagan_Tab_Header=(//h5[@title='McLagan'])[2]
ACC_MC_1_Mclagan_Tab_Headercount=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th/text()
ACC_MC_1_Mclagan_Tab_rowcount=//table[contains(@id,'Mclagan_table')]//tbody//tr
ACC_MC_1_Mclagan_Tab_Header_period=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th[@data-fixedid='period']/text()
ACC_MC_1_Mclagan_Tab_Header_FirmRevenue=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th[@data-fixedid='Firm Revenue']/text()
ACC_MC_1_Mclagan_Tab_Header_Market_Revenue=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th[@data-fixedid='Market Revenue']/text()
ACC_MC_1_Mclagan_Tab_Header_Benchmark=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th[@data-fixedid='opp2']/text()
ACC_MC_1_Mclagan_Tab_Header_Frim_share=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th[@data-fixedid='FirmMarketShare']/text()
ACC_MC_1_Mclagan_Tab_Header_FrimRank=//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th[@data-fixedid='FirmRank']/text()
ACC_MC_1_Mclagan_Tab_Header_IndexPosition=//table[contains(@id,'Mclagan_table')]//tbody//tr[rowvalue]//td[indexvalue]

//table[contains(@class,'mclagan_report_table custDataTable theme-table table-bordered nowrap dataTable no-footer')]//th/text()
//ACC_MC_1_Mclagan_Tab_Header_period=//div[@class='dataTables_scrollHead']//table//thead//th[@data-fixedid='period']




ACC_MC_1_Mclagan_Tab_Year(//li[@data-range-key='03/18/2021'])[2]



