Prism_SimpleListValidate= M_S_1_1

RevenueModule     = //li[@data-module='Revenue']/a[@class='menuWithSub']
RevenueSubModule_Trade  =//li[@data-module='Trades']/a
MyListModule=//li[@data-module='My Lists V3']/a

PrismUpdate_ToastClose=//button[@class='toast-close-button']

M_S_1_id_ListToggles_Right=//i[@class='fa expand-collapse pull-right fa-angle-double-right']
M_S_1_id_ListToggles_Left=//i[@class='fa expand-collapse pull-right fa-angle-double-left']
M_S_1_id_ListToggles_LeftClick=//i[@id='listtoggle']
M_S_1_id_SelectedList=(//*[@id="myList"]/ul//li[@class='list-menu-li active'])
M_S_1_id_SelectedListName=(//*[@id="myList"]/ul//li[@class='list-menu-li active']//div[@class='tab-list-name'])
M_S_1_id_dropdownSel=(//span[@class='caret'])[3]
M_S_1_id_RecentlyCreatedClick=//ul[@class=' listSort dropdown-menu']//a[@data-value='newFirst']
M_S_1_id_3dots_Click=(//*[@id="myList"]/ul//li[@class='list-menu-li active'])//span[@data-toggle='dropdown']
//M_S_1_id_ShareIcon_Click=//a[@class='sharelist active']
//M_S_1_id_Top_ShareIcon_Click=//button[@class='icon icon-share-2 icon-xs clr-primary']
M_S_1_id_ShareIcon_Click=//*[@id="myList"]/ul//li[@data-listname='Simple']//child::*[contains(@class,"sharelist")]
M_S_1_id_ToastCloseButton=//button[@class='toast-close-button']
M_S_1_id_PrismToastCloseButton=//button[@class='toast-close-button']
M_S_1_id_CrossCloseButton=//div[@id='list-multi-share']//div[@class='modal-header bg-primaryLight']//button[1]

Share Button:
M_S_1_id_Share_Buttonclick=//button[@class='icon icon-share-2 icon-xs clr-primary']
M_S_1_id_ShareList_Header=//h4[text()='Share List']
M_S_1_id_ShareListname=//ul[@id='list-namessearch']//input
M_S_1_id_Names_DrpDownClick=//ul[@class='Dropdown']//li[1]
M_S_1_id_ChooseEmployee=//ul[@id='selectUsersearch']//input
M_S_1_id_Share_Btn=//button[@id='shareMultiList']
M_S_1_id_Confirmation_Btn=//button[@id='modal_share_send_yes']
M_S_1_id_CloseWindow_Confirmation_Btn=//button[@id='modal_share_yes']


LogOut:
M_S_1_id_EquityHead_Label_Click=//label[@class='default-img bg-primaryLight']
M_S_1_id_EquityHead_LogOut_Click=//ul[@class='dropdown-menu animated fadeInDown profile-drpdown']//a[@class='send font-md']



AnalystLogin:
M_S_1_id_ListNAMe=(//*[@id="myList"]//ul[@class='list-mgt-listdtls m-t-xs']//li[@list-type='Static']//div[@class='tab-list-name'])[1]

Analyst Logout:
M_S_1_id_Analyst_Label_Click=//span[@class='m-t-xs  m-r-md usr_name profileName']
M_S_1_id_Analyst_LogOut_Click=//ul[@class='dropdown-menu animated fadeInDown profile-drpdown']//a[@class='send font-md']

Table:
M_S_1_id_Table_RowCount=//div[@class='dataTables_scrollBody']//table[@id='shareListInfo']//tbody//tr
M_S_1_id_Table_HeadersCount=//div[@class='dataTables_scrollHeadInner']//table[@class='compact table theme-table data-ellipsis table-bordered table-striped custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//thead//tr[2]//th
M_S_1_id_EmployeName=//div[@class='dataTables_scrollHeadInner']//table[@class='compact table theme-table data-ellipsis table-bordered table-striped custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//thead//tr[2]//th[text()='Employee Name']
M_S_1_id_Existing_Acess=//div[@class='dataTables_scrollHeadInner']//table[@class='compact table theme-table data-ellipsis table-bordered table-striped custmultiHeaderDataTable theme-multiheader nowrap dataTable no-footer']//thead//tr[2]//th[text()='Existing Access']
EE_1_1_Eventinfo_empName_indexposition=//div[@class='dataTables_scrollBody']//table[@id='shareListInfo']//tbody//tr[rrow]//td[indexposition]
EE_1_1_Eventinfo_ExistAccess_indexposition=//div[@class='dataTables_scrollBody']//table[@id='shareListInfo']//tbody//tr[rrow]//td[indexposition]

Delet :
M_S_1_id_Table_Analyst_Viewonlydelete=(//table[@id='shareListInfo']//tbody//tr//td[@class='border-all dt-center delEmp'])[1]
M_S_1_id_Table_Sales_Viewonlydelete=(//table[@id='shareListInfo']//tbody//tr//td[@class='border-all dt-center delEmp'])[3]
M_S_1_id_Delete_Confir_Btn=//button[@id='modal_sharedel_yes']


M_S_1_id_Create_SimplList_Btn=(//button[@class='icon icon-menu-new-account icon-xs clr-primary'])
M_S_1_id_Listname_SearchBox=//input[@id='list-name']
M_S_1_id_Check_SimpleRadioSelected=//input[@id='simpleList']
M_S_1_id_List_SaveBtn=//button[@id='saveList']
M_S_1_id_Add_QuickContact_TabClick=//div[@class='top-buttons quickaddcontactheader staticoptions']
M_S_1_QuickContact_Serarch=//ul[@id='undefinedsearch']//li[@class='TokenSearch']//input
M_S_1_QuickContact_Serarch_Dropdown=//ul[@class='Dropdown']//li[1]
M_S_1_AddContact_Btn=//button[@class='btn-custom btn-green btnAddContact']
M_S_1_ListName_Close=//i[@class='icon icon-close']

Contact:
M_S_1_ContactName_Header=//div[@id='search_header_slide']
M_S_1_ContactName_Click=(//a[@data-matchedkey='name'])[1]
M_S_1_My_List_wizard=//div[@class='ibox-title panel_content_handle']/h5[@title='My Lists']
M_S_1_My_List_count=//table[@data-fixedid='tccontacttearsheetlisttable']//tbody//tr[row]
M_S_1_My_AddedList_count=//ul[@class='dropdown-menu contact_out_submenu']//li[count]
M_S_1_AddList_Btn_Click=(//button[@data-toggle='dropdown'])[1]
M_S_1_Contact_tearsheet_Close=//button[@title='Close']

M_S_1_id_SimpleList_Click=(//*[@id="myList"]/ul/li[@list-type ='Static']/a/span[not(contains(text(),"(0)"))])[1]
M_S_1_id_SimpleList_Count=(//*[@id="myList"]/ul/li[@list-type ='Static']/a/span)
M_S_1_id_SimpleList_Count1=(//*[@id="myList"]/ul/li[@list-type ='Static']/a//div[contains(@title, ' ')])[temp]


M_S_1_id_Radio_Btn=//input[@id='viewonly']
M_S_1_id_viewandEdit_Radio_Btn=//input[@id='viewandedit']


LP_1_id_useremail=//input[@id='email']
LP_1_id_userpassword=//input[@id='paswd']
LP_1_id_loginButton=//*[@id='login_tb1']//button[@type='button']
LP_1_id_Loadedelement=//*[@id='prism_feedback']


 Xl TestCase :
Values:TestcasePath	
	M_S_1_v_testCasePath =\\TestCases\\SimpleList\\Mylist_simplelist.xlsx
	M_S_1_v_Row=row id
    M_S_1_v_ListName=List Name
    M_S_1_v_ContactName=Contact Name1
    M_S_1_v_ContactName2=Contact Name2
    M_S_1_v_AnalystName_View=Analyst View
    M_S_1_v_AnalystName_ViewandEdit=Analyst ViewandEdit
    M_S_1_v_SalespersonName_View=Salesview
    M_S_1_v_SalespersonName_ViewandEdit=SalesViewandEdit
    M_S_1_v_ViewBtn= ViewButton
    M_S_1_v_ViewAndEdit_Btn= ViewAndEdit
    M_S_1_v_EquityHeadName=EquityHeadName
    M_S_1_v_Sales_UserName= Sales_UserName
    M_S_1_v_Sales_password= Sales_password
    LP_1_v_useremail=Analyst_UserName
    LP_1_v_userpassword=Analyst_password
    M_S_1_v_Equi_useremail=Equity_UserName
    M_S_1_v_Equi_userpassword=Equity_password
    M_S_1_v_Search_contactName=GlobalContactName
    
    
Toast Msg:
M_S_1_v_AddContact_toast=List saved
M_S_1_v_ShareToast_msg=List share settings changed.
M_S_1_v_ListCreated=List saved







