RevenueModuleWebElements= RM_1
	RM_1_id_revenue_module_icon = //div[@id='mCSB_1_container']//a[@class='menuWithSub']//button[@class='icon menu-svg icon-sm icon-money-bag']
	RM_1_id_sub_revenue_tab = //div[@id='mCSB_1_container']//li//li[@data-module='Revenue']/a
	RM_1_id_revenue_advanced_tab = //div[@id='mCSB_1_container']//li[@data-module='Revenue (Advanced)']/a
	RM_1_id_revenue_trades_tab = //div[@id='mCSB_1_container']//li[@data-module='Trades']/a
	RM_1_id_revenue_ROI_tab = //div[@id='mCSB_1_container']//li[@data-module='ROI']/a
	RM_1_id_revenue_McLagan_tab = //div[@id='mCSB_1_container']//li[@data-module='McLagan']/a
	RM_1_id_revenue_review_tab = //div[@id='mCSB_1_container']//li[@data-module='Review']/a
	RM_1_id_revenue_by_account_tab= //*[@data-tabid='tab-account']
	RM_1_id_revenue_by_person_tab= //*[@data-tabid='tab-person']
	RM_1_id_revenue_by_product_tab = //*[@data-tabid='tab-product']
	RM_1_id_revenue_by_region_tab = //*[@data-tabid='tab-region']
	RM_1_id_revenue_by_team_tab = //*[@data-tabid='tab-team']
	RM_1_id_revenue_by_account_filter_search = //*[@id='dataTable_tab-account_rep_4_4_13_account_filter']//input
	RM_1_id_revenue_by_person_filter_search = //*[@id='dataTable_tab-person_rep_4_4_13_person_filter']//input
	RM_1_id_revenue_by_team_filter_search = //*[@id='dataTable_tab-team_rep_4_4_13_team_filter']//input
	
Revenue_values:
	RM_1_v_revenue_by_account_tab= Revenue By Account
	RM_1_v_revenue_by_person_tab= Revenue By Person
	RM_1_v_revenue_by_product_tab = Revenue By Product
	RM_1_v_revenue_by_region_tab = Revenue By Region
	RM_1_v_revenue_by_team_tab = Revenue By Team
	
	