ApplicationURL			=	http://192.168.3.110:84/prismst/home.html
EnviromentName          =   110
1_ChromeDriverPath		=	\\Resources\\BrowserDrivers\\chromedriver.exe
2_IEDriverPath			=	\\Resources\\BrowserDrivers\\IEDriverServer.exe
3_FireFoxDriverPath		=	\\Resources\\BrowserDrivers\\geckodriver.exe
BrowserType				=	1
ReportFilePathWithName	=	F:\\Reports\\TestResults

1= success, 2= failure, 3=both
screenshottype = 3

Report_Config:3
	3_con_html_report_title = Prism Test Report
	3_con_report_name = Prism Test Results and it's Status

ModuleConfig:(if you want particular module should'nt run, then set it to 0)	
 
	ProductionMode      			= true
	mylist		  					= 0 
	contactcreation             	= 0	 
	accountcreation 				= 0
	ContactMove                     = 0
	EmploymentChange				= 0
	activity						= 0
	ExistingContactverification 	= 0	
	ExistingInteractionverification = 0
	Trades                          = 0 
	SpecialCharater                 = 0
	feedback						= 0
	eventmanager					= 0
	accountverification				= 0
	contactverification				= 0
	ProductionBugs					= 1
	ContactInterest					= 0
	   	 
 
