110 URl:

110_My_Lists = My Lists V3
110_Activity = Activity,Activity

-----------------------------------------
28 URL:

28_My_Lists = My Lists
28_Activity = Activity,Activity

------------------------------------------
Chardan URL:

Chardan_My_Lists = My List 

------------------------------------------


CraigHallum URL:

CraigHallum_My_Lists = My List

--------------------------------------------
CapitalOne URL:

CapitalOne_My_Lists  = My List

--------------------------------------------
RenMac URL:

RenMac_My_Lists  = My List
RenMac_Activity  = Activity

-----------------------------------------

MKM URL:

MKM_My_Lists  = My Lists






