trades_id = T_1

Element Filter ID:
T_1_id_pagenation_count = //*[@class="paginate_button "][last()]/a
T_1_id_filter_on_off    = //*[contains(@id,"onoff_trade_filter")]//parent::*
T_1_id_filter_container  =//*[@id="accordion"]
T_1_id_filter_Employee_name =  //ul[@id="emp_nameToksearch"]	
T_1_id_filter_ticker         =//ul[@id="tickerToksearch"]	 
T_1_id_filter_product        =//ul[@id="productToksearch"]
T_1_id_filter_desk           =//ul[@id="deskToksearch"]
T_1_id_filter_account_name   =//ul[@id="acc_nameToksearch"]
T_1_id_filter_type           =//ul[@id="typeToksearch"]
T_1_id_filter_transaction_id =//ul[@id="tranidToksearch"]
T_1_id_filter_splite_id      = //ul[@id="ae_split_idToksearch"]
T_1_id_filter_short_code     =//ul[@id="mgmt_codeToksearch"]
Need Fixed id
T_1_id_filter_apply_all      = //*[contains(text(),"Apply All")]	 
T_1_id_filter_clear_all      =//*[contains(text(),"Clear All")]	

Table Filter Text:
---------Need Fixed id----------
T_1_id_emp_name_text     = //*[@class="emp_nameText"]
T_1_id_ticker_text       =//*[@class="tickerText"]
T_1_id_product_text      =	//*[@class="productText"]
T_1_id_desk_text         = //*[@class="deskText"]
T_1_id_account_name_text      =//*[@class="acc_nameText"]
T_1_id_type_text         =//*[@class="typeText"]
T_1_id_transaction_id_text =//*[@class="tranidText"]
T_1_id_sub_type          =//*[@class="subtypeText"]
T_1_id_splite_text       =//*[@class="ae_split_idText"]
T_1_id_code_text         =//*[@class="mgmt_codeText"]

table data:
T_1_id_table_header           = //table[contains(@class,"compact")]/thead/tr[2]/th[@tabindex]	
T_1_id_table_body        	  = //table[contains(@id,"trade-summary")]/tbody/tr
T_1_id_table_header_total_value = (//table[contains(@class,"compact")]/thead/tr[1])[1]/th

table pagination:

T_1_id_last_page_table        = //li[@class="paginate_button "][last()]/a
T_1_id_page_next_button       = //li[contains(@id,"next")]

Trades Excel Values:
T_1_v_testCasePath = \\TestCases\\trades\\T_1.xlsx
T_1_v_row_id = Row_id
T_1_v_employment_name = Emp Name 
T_1_v_ticker = Ticker
T_1_v_product = Product
T_1_v_Desk    =Desk
T_1_v_account_name =Account Name

Trades table columns:
T_1_v_gross_comm = Gross Comm.
T_1_v_quantity   = # Quantity
T_1_v_net_value  = Net Value
 
