call AccountCoverageManagementTest.bat
cd RunFiles/CANTOR
call AccountTearSheetArchiveTest.bat
cd RunFiles/CANTOR
call AccountTearsheetBulkAddContactTest.bat
cd RunFiles/CANTOR
call AccountTearSheetTest.bat
cd RunFiles/CANTOR
call ActivityShowFilter.bat
cd RunFiles/CANTOR
call ActivityTest.bat
cd RunFiles/CANTOR
call AddContactTest.bat
cd RunFiles/CANTOR
call AddCorporateAccountTest.bat
cd RunFiles/CANTOR
call AddCoverage.bat
cd RunFiles/CANTOR
call AddInteractionTest.bat
cd RunFiles/CANTOR
call AddInvestorAccountTest.bat
cd RunFiles/CANTOR
call AddNewContactTest.bat
cd RunFiles/CANTOR
call AddRecommendationTest.bat
cd RunFiles/CANTOR
call AddServiceAccountTest.bat
cd RunFiles/CANTOR
call AnalystTearsheetTest.bat
cd RunFiles/CANTOR
call BulkAddContactsTest.bat
cd RunFiles/CANTOR
call BulkCallTest.bat
cd RunFiles/CANTOR
call BulkMoveTest.bat
cd RunFiles/CANTOR
call BulkSubscription.bat
cd RunFiles/CANTOR
call ContactRelationshipTest.bat
cd RunFiles/CANTOR
call ContactTearSheetHeadersVerify.bat
cd RunFiles/CANTOR
call ContactTearSheetTest.bat
cd RunFiles/CANTOR
call DashboardTest.bat
cd RunFiles/CANTOR
call EmailsModuleTest.bat
cd RunFiles/CANTOR
call FloatingATSTest.bat
cd RunFiles/CANTOR
call FloatingCTSTest.bat
cd RunFiles/CANTOR
call FloatingTTSTest.bat
cd RunFiles/CANTOR
call GlobalSearchTest.bat
cd RunFiles/CANTOR
call LibraryPortalTest.bat
cd RunFiles/CANTOR
call MarModuleTest.bat
cd RunFiles/CANTOR
call MyContactsTest.bat
cd RunFiles/CANTOR
call MyListTest.bat
cd RunFiles/CANTOR
call ProspectTest.bat
cd RunFiles/CANTOR
call QuickLookBulkAddContactsTest.bat
cd RunFiles/CANTOR
call ReaderShipEmailModule.bat
cd RunFiles/CANTOR
call ReaderShipModule.bat
cd RunFiles/CANTOR
call RelationshipEnhancements.bat
cd RunFiles/CANTOR
call ReportTest.bat
cd RunFiles/CANTOR
call ResearchLibraryModuleTest.bat
cd RunFiles/CANTOR
call ResearchSalesPeronTearsheet.bat
cd RunFiles/CANTOR
call RevenueAdvancedAllTableHeaders.bat
cd RunFiles/CANTOR
call RevenueAdvancedTest.bat
cd RunFiles/CANTOR
call RevenueModule.bat
cd RunFiles/CANTOR
call RevenueTableExample.bat
cd RunFiles/CANTOR
call RevenueTest.bat
cd RunFiles/CANTOR
call ROITest.bat
cd RunFiles/CANTOR
call RoleNavigationTest.bat
cd RunFiles/CANTOR
call SalesTraderTearSheetTest.bat
cd RunFiles/CANTOR
call ServiceAccountTearsheetBulkAddContactTest.bat
cd RunFiles/CANTOR
call ServiceAccountTest.bat
cd RunFiles/CANTOR
call SponserCompaniesTab.bat
cd RunFiles/CANTOR
call SuperAccountTest.bat
cd RunFiles/CANTOR
call TickerCoverageManagementTest.bat
cd RunFiles/CANTOR
call TickerTearsheetBulkAddContactTest.bat
cd RunFiles/CANTOR
call TickerTearSheetTest.bat
cd RunFiles/CANTOR
call TopResearchSalesPerson.bat
cd RunFiles/CANTOR
call TopSalesTradersGrossComm.bat
cd RunFiles/CANTOR
call TradesModule.bat
cmd /k
