AddInteractionWebElements=AI_1
	AI_1_id_action_plus_icon        = header_action_button_icon
	AI_1_id_add_interaction_button  = //*[@id="headerAddInteraction"]
	AI_1_id_contact_token_search	= //*[@id="search_interaction_contactsearch"]//input
	AI_1_id_contact_token_dropdown  = //*[@id="contactTokens"]//ul[@class="Dropdown"]
	AI_1_id_single_interaction		= //*[@id="single_interaction"]
	AI_1_id_multiple_interaction 	= //*[@id="multi_interaction"]
	AI_1_id_interaction_date		= //*[@id="interactionDt"]
	AI_1_id_actitvity_type			= //select[@id="activityType"]
	AI_1_id_duration 				= //*[@id="callduration"]
	AI_1_id_subject					= //*[@id="subject"]
	AI_1_id_comments 				= //*[@id="input-meetingNotes"]
	AI_1_id_tags_search 			= //*[@id="tagTokenssearch"]//input
	AI_1_id_tags_search_dropdown	= //div[@data-fixedid="log_interaction_tags"]//ul[@class="Dropdown"]
	AI_1_id_internal_att_search		= //*[@id="internalattendeessearch"]//input
	AI_1_id_internal_attendee		= //div[@data-fixedid="log_interaction_intattendees"]//ul[@class="Dropdown"]
	AI_1_id_alertcvg_yes_no			= //*[@id="alertcovgteambtn"]
	AI_1_id_alertcvg_Reseachsales	= //*[@id="sales"]
	AI_1_id_alertcvg_salestrader	= //*[@id="trades"]
	AI_1_id_alertcvg_analyst		= //*[@id="analyst"]
	AI_1_id_alertcvg_positiontrader = //*[@id="ptrader"]
	AI_1_id_alertcvg_FI				= //*[@id="r_dcm"]
	AI_1_id_alertcvg_internal		= //*[@id="others"]
	AI_1_id_internalsearch			= //*[@id="othersListsearch"]	
	AI_1_id_interacttion_savebtn	= //*[@id="submitLogInteraction"]
	AI_1_id_interaction_date_id		= interactionDt
	AI_1_id_closeInteractionPopup	= interactionPopupClose
	AI_1_id_InteractionCloseYes		= intrCloseConf
	AI_1_id_AlertCvgInput			= alert_team
	AI_1_id_Activity_searchBar		= //*[@id="activityListTable"]//input[@type="search"]
	AI_1_id_activityTableBody		= //*[@id="activityListTable"]//*[@class="dataTables_scrollBody"]//tbody//tr[@role="row"]
	AI_1_id_tearSheetCloseBtn		= //*[@id="panelHeadTab"]//li//button[@title="Close"]
	AI_1_id_emptyrowcheck			= //*[@id="activityListTable"]//*[@class="dataTables_scrollBody"]//tbody//tr//td[text()="No data available in table"]
    AI_1_id_Activity_empty_row      = //div[@id='activityListTable']//tbody/tr/td[@class='dataTables_empty']
MandatoryFiledValidationRowConfig:
	AI_1_v_testCasePath    			= \\TestCases\\activity\\AI_1.xlsx
	AI_1_v_contactrow				= ContactName
	AI_1_v_interactiondaterow		= InteractionDate
	AI_1_v_activitytyperow			= ActivityType
	AI_1_v_commentsrow				= Comments
	AI_1_v_rowid					= rowid

MandatoryFiledToastTextConfig:
	AI_1_v_ContactFiled				= Please select a contact
	AI_1_v_Activity_Type			= Select the activity type
	AI_1_v_Comments					= Comments cannot be empty
	
AddInteractionValuesRowConfig:
	AI_1_v_rowidVal					= addrowid
	AI_1_v_contacts					= addcontacts
	AI_1_v_typeofinteraction		= addtypeofinteraction
	AI_1_v_interactiondate			= addinteractiondate
	AI_1_v_activitytype				= addactivitytype
	AI_1_v_duration					= duration
	AI_1_v_subject					= subject
	AI_1_v_comments					= comments
	AI_1_v_tags						= tags
	AI_1_v_internalattentee			= internalattentee
	AI_1_v_isalertcoverage			= isalertcoverage
	AI_1_v_alertcoverageType		= alertcoverageType
	AI_1_v_coveragedata				= coveragedata