FeedBack_Submit = FB_1
	FeedBack_Web_Elements:
		FB_1_id_feedback_click = prism_feedback
		FB_1_id_emoji_type = //*[@id='myratings']//*[text()='tempValue']
		FB_1_id_feedback_textbox = //*[@id='feedbackModal']//textarea
		FB_1_id_feedback_submit_button = //*[@id='feedbackModal']//div[@class='modal-footer']//button
	
	FeedBack_Values:
		FB_1_v_case_from_excel = 1
		FB_1_v_testCasePath = \\TestCases\\Feedback\\FB_1.xlsx
		FB_1_v_rowid = rowid
		FB_1_v_emoji_type = Emoji Type
		FB_1_v_category_type = Category
		FB_1_v_feedback_textbox = FeedBack Description
		FB_1_v_error_toast_message = Please enter your feedback
		FB_1_v_success_toast_message =  Thank you. Your feedback has been submitted.