Login_Submit = LP_1
	Login_in_Web_Elements:
		LP_1_id_useremail    = //input[@id='email']
		LP_1_id_userpassword = //input[@id='paswd']
		LP_1_id_loginButton = //*[@value='Login']
		LP_1_id_loginType = //select[@id='login_type']
		LP_1_id_errorlabel   = //*[@id='content']
		LP_1_id_Loadedelement= //*[@id='prism_feedback']
		LP_1_id_profileButton= //li[@title="Profile Settings"]//span//label
		LP_1_id_LogoutButton = button[value="Login"]
	Values:
		LP_1_v_case_from_excel = 1
		LP_1_v_testCasePath    = \\TestCases\\login\\LP_1.xlsx
		LP_1_v_useremail       = username
		LP_1_v_userpassword    = password
		LP_1_v_rowid           = rowid
	Default_User:
		LP_1_v_default_Login_user= equity
		LP_1_v_default_Pass      = new
		

Login credentials:
28_UAT:
	28_UAT_user = prism
	28_UAT_pass = new
	28_UAT_type = Prism Login
	
	
28_UAT_Admin_Console:
28_UAT_Admin_Console_user = admin
28_UAT_Admin_Console_pass = admin123

#Server1
110_UAT:
	110_UAT_user = equity
	110_UAT_pass = new
	110_UAT_type =
--------------------------------------------

#Server2 
QA1_UAT:
	110_UAT_user = equity
	110_UAT_pass = new
	110_UAT_type =
	
---------------------------------------------	

CapitalOne_UAT:
	CapitalOne_UAT_user = Hussain
	CapitalOne_UAT_pass = hussain
	CapitalOne_UAT_type = Prism Login

CapitalOne_UAT_Admin_Console:	
	CapitalOne_UAT_Admin_Console_user =admin
	CapitalOne_UAT_Admin_Console_pass =admin123
	
CapitalOne_Prod:
	CapitalOne_Prod_user =
	CapitalOne_Prod_pass =
CapitalOne_QA:
	CapitalOne_QA_user = 
	CapitalOne_QA_pass = 
	
CapitalOne_QA_Admin_Console:	
	CapitalOne_QA_Admin_Console_user =admin
	CapitalOne_QA_Admin_Console_pass =admin123
--------------------------------------------

Roth_UAT:
 
	Roth_UAT_user =Kowsalya
	Roth_UAT_pass =Welcome@1
	Roth_UAT_type =Prism Login

Roth_Prod:
	Roth_Prod_user =kowsalya
	Roth_Prod_pass =new
	Roth_Prod_type =Prism Login
--------------------------------------------	


RosenBlatt_UAT:
 
	RosenBlatt_UAT_user =Kowsalya@datazoic.com
	RosenBlatt_UAT_pass =
	RosenBlatt_UAT_type =Prism Login

Roth_Prod:
	RosenBlatt_Prod_user =kowsalya@datazoic.com
	RosenBlatt_Prod_pass =Rosen@123
    RosenBlatt_Prod_type =Prism Login
--------------------------------------------	


	 
Sidoti_UAT:
	Sidoti_UAT_user =kowsalya
	Sidoti_UAT_pass =Sidoti@2023
	Sidoti_UAT_type = Prism Login

Sidoti_Prod:
	Sidoti_Prod_user =kowsalya@datazoic.com
	Sidoti_Prod_pass =Kowsi@12
	Sidoti_Prod_type =LDAP Login
--------------------------------------------	

RenMac_UAT:
	RenMac_UAT_user = Hussain
	RenMac_UAT_pass = Prism@1234
	RenMac_UAT_type = 

RenMac_Prod:
	RenMac_Prod_user = Daniel.francis
	RenMac_Prod_pass = Equity@12345
	RenMac_UAT_type =
--------------------------------------------------------

CraigHallum_UAT
	CraigHallum_UAT_user = Shamily
	CraigHallum_UAT_pass = Shamily@12345
    CraigHallum_UAT_type = Prism Login
	
	
CraigHallum_Prod:
	CraigHallum_Prod_user =Shamily
	CraigHallum_Prod_pass =Salman@1234
	CraigHallum_Prod_type = Prism Login

110_UAT_Admin_Console:
	110_UAT_Admin_Console_user = admin
	110_UAT_Admin_Console_pass = admin123
	
110_UAT_FI_User:
	110_UAT_FI_user = fihead
	110_UAT_FI_pass = new
	
28_UAT
	28_UAT_user = prism
	28_UAT_pass = new
	28_UAT_type = Prism Login
 
Chardan_UAT
    Chardan_UAT_user = kowsalya
    Chardan_UAT_pass = Welcome@1
    Chardan_UAT_type = Prism Login
    
Chardan_Prod
    Chardan_Prod_user = kowsalya
    Chardan_Prod_pass = New
    Chardan_Prod_type = Prism Login
    
WilliamBlair UAT:    
   WilliamBlair_UAT_user =GP93639
   WilliamBlair_UAT_pass =Gold@7970
   
   WilliamBlair_UAT_Console_user=Karthik
    WilliamBlair_UAT_Console_pass = Karthik@1 
     
Cantor UAT:

    Cantor_UAT_user = Elavarasan
    Cantor_UAT_pass = New@1234
    Cantor_UAT_type = Prism Login

Cantor Prod:
    Cantor_Prod_user = AM131627
    Cantor_Prod_pass = Chang0MeNowASAP!
    Cantor_Prod_type = LDAP


Mizuho UAT:

    Mizuho_UAT_user =KT7220
    Mizuho_UAT_pass =2023Mizuho123!
    Mizuho_UAT_type =LDAP

-----------------------------------------
Liberum Prod:

	Liberum_UAT_user	=Kowsalya
	Liberum_UAT_pass	=Welcome
	Liberum_UAT_type	=Prism Login


Liberum Prod:

	Liberum_Prod_user	=Kowsalya
	Liberum_Prod_pass	=Welcome
	Liberum_Prod_type	=Prism Login

Piper_UAT:
	Piper_UAT_user =VIJAA10
	Piper_UAT_pass =Datazoic2023!
	Piper_UAT_type = 

Piper_Prod:
	Piper_Prod_user =Shamily
	Piper_Prod_pass =Shamily@123
	Piper_Prod_type =
	
Stephens_UAT:
	Stephens_UAT_user=skhan99
	Stephens_UAT_pass=Salmanqaauto$20231
	Stephens_UAT_type = 
	
Stephens_Prod:
	Stephens_Prod_user=skhan99
	Stephens_Prod_pass=Salmanqaauto$20231
	Stephens_Prod_type = 
