EnviromentName          =  CraigHallum
1_ChromeDriverPath		=	./Resources/BrowserDrivers/chromedriver.exe
2_IEDriverPath			=	\\Resources\\BrowserDrivers\\IEDriverServer.exe
3_FireFoxDriverPath		=	\\Resources\\BrowserDrivers\\geckodriver.exe
4_Period_Pattern        =   MM/dd/yyyy
BrowserType				=	chrome
ReportFilePathWithName	=	F:\\Reports\\Sidoti
RetryCount				=	1
headless				=	true
remoteurl               =   http://localhost:4444/wd/hub
remote					= 	false
1= success, 2= failure, 3=both
screenshottype = 3

Report_Config:3
	3_con_html_report_title = Prism Test Report
	3_con_report_name = Prism Test Results and it's Status

ModuleConfig:(if you want particular module should'nt run, then set it to 0)	
	ProductionMode      		= true
	mylist		  				= 0
	feedback					= 0
	eventmanager				= 0
	activity					= 0
	accountverification			= 0
	contactverification			= 0
	ProductionBugs				= 0
	AccountCreation				= 0
	ContactInterest				= 0


Environment URls:
 
 110_UAT=https://192.168.3.110/prismST/home.html
 110_UAT_Admin_Console = http://192.168.3.110:84/prismSTadmin/admin_master.php
 
 28_UAT = http://192.168.3.28:84/prismst/home.html
 28_UAT_Admin_Console = http://192.168.3.110:84/prismSTadmin/admin_master.php
 
 QA1_UAT=https://192.168.3.110:1443/prismST/home.html
 
 CapitalOne_UAT	 =	https://capitaloneuat.datazoic.com/coprismst/home.html
 CapitalOne_Prod =	https://capitalone.datazoic.com/coprismst/home.html
 CapitalOne_QA = https://capitaloneqa.datazoic.com/prismst/
 
 Roth_UAT =https://rothuat.datazoic.com/prismst/home.html
 Roth_Prod=https://roth.datazoic.com/prismst/home.html

RosenBlatt_UAT =https://rosenblatt.datazoic.com/prismst/home.html
RosenBlatt_Prod=https://rosenblatt.datazoic.com/prismst/home.html

 Sidoti_UAT = https://sidotiuat.datazoic.com/prismst/home.html#
 Sidoti_Prod = https://sidoti.datazoic.com/prismst/home.html
 
 RenMac_UAT = https://renmacuat.datazoic.com/renmacst/home.html#
 RenMac_Prod = https://renmac.datazoic.com/renmacst/home.html
 
 CraigHallum_UAT =https://craighallumuat.datazoic.com/chprismst/home.html
 CraigHallum_Prod=https://craighallum.datazoic.com/chprismst/home.html
  
 Chardan_UAT = https://chardanuat.datazoic.com/chardanst/home.html
 Chardan_Prod=https://chardanst.datazoic.com/chardanst/home.html
 
 WilliamBlair_UAT_Admin_Console = https://prism.blairnet.net/prismstadmin/admin_master.php?type=30
 WilliamBlair_UAT = https://prismqa.blairnet.net/prismst/home.html#pages/10/23

 Cantor_UAT =  http://prism_app_dev.cad.local:86/web/cantor/home.html
 Cantor_Prod = http://prism.cad.local/web/cantor/home.html
 
 Mizuho_UAT = https://craighallumuat.datazoic.com/chprismst/home.html#
 Mizuho_Prod=http://craighallum.datazoic.com/chprismst/home.html

 Piper_UAT = http://prismuat.psc.com/prismst/home.html
 Piper_Prod= http://prism.psc.com/prismst/home.html

Liberum_UAT=https://liberumuat.datazoic.com/prismst/home.html
Liberum_Prod=https://liberum.datazoic.com/prismst/home.html
 
 Stephens_UAT = https://prismuat.stephens.com/prismst/home.html
 Stephens_Prod = https://prism.stephens.com/prismst/home.html
