call AccountCoverageManagementTest.bat
cd RunFiles/STEPHENS
call AccountTearSheetArchiveTest.bat
cd RunFiles/STEPHENS
call AccountTearSheetTest.bat
cd RunFiles/STEPHENS
call ActivityShowFilter.bat
cd RunFiles/STEPHENS
call ActivityTest.bat
cd RunFiles/STEPHENS
call AddContactTest.bat
cd RunFiles/STEPHENS
call AddCorporateAccountTest.bat
cd RunFiles/STEPHENS
call AddCoverage.bat
cd RunFiles/STEPHENS
call AddCoverageFromTickerTearSheet.bat
cd RunFiles/STEPHENS
call AddCoverageWithSector.bat
cd RunFiles/STEPHENS
call AddInteractionTest.bat
cd RunFiles/STEPHENS
call AddInvestorAccountTest.bat
cd RunFiles/STEPHENS
call AddNewContactTest.bat
cd RunFiles/STEPHENS
call AddRecommendationTest.bat
cd RunFiles/STEPHENS
call AddServiceAccountTest.bat
cd RunFiles/STEPHENS
call BulkAddContactsTest.bat
cd RunFiles/STEPHENS
call BulkCallTest.bat
cd RunFiles/STEPHENS
call BulkEmploymentChangeTest.bat
cd RunFiles/STEPHENS
call BulkMoveTest.bat
cd RunFiles/STEPHENS
call BulkSubscription.bat
cd RunFiles/STEPHENS
call ContactRelationshipTest.bat
cd RunFiles/STEPHENS
call ContactTearSheetHeadersVerify.bat
cd RunFiles/STEPHENS
call ContactTearSheetTest.bat
cd RunFiles/STEPHENS
call DashboardTest.bat
cd RunFiles/STEPHENS
call FloatingATSTest.bat
cd RunFiles/STEPHENS
call FloatingCTSTest.bat
cd RunFiles/STEPHENS
call FloatingTTSTest.bat
cd RunFiles/STEPHENS
call GlobalSearchTest.bat
cd RunFiles/STEPHENS
call LibraryPortalTest.bat
cd RunFiles/STEPHENS
call MyContactsTest.bat
cd RunFiles/STEPHENS
call MyListTest.bat
cd RunFiles/STEPHENS
call NewContactTest.bat
cd RunFiles/STEPHENS
call ProspectTest.bat
cd RunFiles/STEPHENS
call ReaderShipEmailModule.bat
cd RunFiles/STEPHENS
call ReaderShipModule.bat
cd RunFiles/STEPHENS
call RelationshipEnhancements.bat
cd RunFiles/STEPHENS
call ReportTest.bat
cd RunFiles/STEPHENS
call ResearchLibraryModuleTest.bat
cd RunFiles/STEPHENS
call ResearchSalesPeronTearsheet.bat
cd RunFiles/STEPHENS
call RevenueAdvancedTest.bat
cd RunFiles/STEPHENS
call RevenueModule.bat
cd RunFiles/STEPHENS
call RevenueTableExample.bat
cd RunFiles/STEPHENS
call RevenueTest.bat
cd RunFiles/STEPHENS
call ROITest.bat
cd RunFiles/STEPHENS
call SalesTraderTearSheetTest.bat
cd RunFiles/STEPHENS
call ServiceAccountTest.bat
cd RunFiles/STEPHENS
call SponserCompaniesTab.bat
cd RunFiles/STEPHENS
call SuperAccountTest.bat
cd RunFiles/STEPHENS
call TickerCoverageManagementTest.bat
cd RunFiles/STEPHENS
call TickerTearSheetTest.bat
cd RunFiles/STEPHENS
call TopResearchSalesPerson.bat
cd RunFiles/STEPHENS
call TopSalesTradersGrossComm.bat
cd RunFiles/STEPHENS
call TradesModule.bat
cmd /k
